zvmsdk/config.py, zvmsdk/configdrive.py, zvmsdk/dist.py, zvmsdk/utils.py, zvmsdk/vmops.py
I run the pep8 test and fix the errors
=> fix pep8 errors

tests/test_zvmsdk.py, zvmsdk/config.py
I have completed a simple UT for this project but still need to fully compete some cases like test_run_instances ,test_terminate_instance and all the cases under class VOLUMEOps.
all other cases passed the test:
$ python test_zvmsdk.py 
Ran 27 tests in 0.013s
OK
=> Unit test frame

zvmsdk/smutclient.py
warn is not a valid log level.
=> LOG.warn changed to LOG.warning

zvmsdk/database.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py, zvmsdk/volumeop.py
To enable volume feature in nova-virt-zvm driver, I did some changes in
driver, but zCC also need some changes to support it and fix some bugs.
1.fix bug: when guest list if there are guests migrated, the API will
raise error. fix this by add a new functions in database module.
2.fix bug: wwpn and lun should be hexadecimal
3.fix bug: fcp should transfer to lower case before processing.
=> Support driver changes

zthin-parts/zthin/src/smcli.c, zthin-parts/zthin/src/smcliImage.c, zthin-parts/zthin/src/smcliImageDefinition.c, zthin-parts/zthin/src/smcliSystem.c, zthin-parts/zthin/src/smcliVirtual.c
The ID should be "" instead of " "or it lead to potential issue.
=> Fix RACF support bug

smtLayer/vmUtils.py
Add retry for `mkfs` when install fs on vm's dasd
This is related to:
https://github.ibm.com/zvc/planning/issues/735
The root cause is that `udevadm settle` can NOT
guarentee ready and existence status of the device.
Code changes:
- Add sleep and retry for `mkfs` cmd in installFS function
Signed-off-by: QianXi <qianxii@cn.ibm.com>
=> Add retry for `mkfs` when install fs on vm's dasd

smtLayer/vmUtils.py
Add retry for `mkfs` when install fs on vm's dasd
This is related to:
https://github.ibm.com/zvc/planning/issues/735
The root cause is that `udevadm settle` can NOT
guarentee ready and existence status of the device.
Code changes:
- Add sleep and retry for `mkfs` cmd in installFS function
Signed-off-by: QianXi <qianxii@cn.ibm.com>
=> (PR to 1.5.n)Add retry for `mkfs` when install fs on vm's dasd

feilong_meetings/20190905-meeting_notes.md, feilong_meetings/20190919-meeting_notes.md, feilong_meetings/20191003-meeting_notes.md, feilong_meetings/20191017-meeting_notes.md, feilong_meetings/meeting_notes_template.md
=> Add meeting note template and first four Feilong meeting notes

zvmsdk/dist.py, zvmsdk/tests/unit/test_dist.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
When attaching the volumes, the UI shows success, but 'multipath -l'
show nothing about the volumes coming after first one.
This is because we did not process all the WWPNs when confiurating the zlinux.
What's more, Our zlinux discovery the WWPNs itself and target_wwpns given
by openstack contains inative WWPNs. So we choose to dicovery the WWPNs in the
OS and do not use the target_wwpns given by openstack.
=> fix bug of adding multi volumes

feilong_meetings/20191031-meeting_notes.md
=> 20191031 Feilong meeting notes

zthin-parts/zthin/bin/unpackdiskimage
Add unpackdiskimage support to deploy RHCOS on ECKD disk.
=> Support deployRHCOS for ECKD disk.

zthin-parts/scripts/unpackdiskimage
This commit support to deploy RHCOS with single unpackdiskimage script.
=> Support to deploy RHCOS with single unpackdiskimage script. 

zthin-parts/zthin/bin/unpackdiskimage
=> fix syntax error

smtLayer/vmUtils.py
when deploying multiple VMs using FBA xfs image, it will report errors
like:
WARNING: Re-reading the partition table failed with error 16: Device or
resource busy. The kernel still uses the old table. The new table will
be used at the next reboot or after you run partprobe(8) or kpartx(8) syncing disks.
=> fix error of re-reading the partition table failed

feilong_meetings/20191114-meeting_notes.md
=> 20191114 Feilong meeting notes

zthin-parts/scripts/unpackdiskimage, zthin-parts/zthin/bin/unpackdiskimage, zthin-parts/zthin/lib/zthinshellutils
This commit is to deploy RHCOS from FCP disk with unpackdiskimage.
Signed-off-by: XiaoMeiZheng <xmzheng@cn.ibm.com>
=> Support deploy RHCOS from FCP

zthin-parts/zthin/bin/IUCV/iucvserverdaemoninstaller.sh
Ensure IUCV server can be installed and service can be up on RHEL8.
=> Ensure IUCV server can be installed and service can be up on RHEL8

zthin-parts/zthin/bin/IUCV/iucvserverdaemoninstaller.sh
Support rhel8 can install and setup iucv server.
=> Support rhel8 can install and setup iucv server

zvmsdk/dist.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/tests/unit/test_dist.py
=> Rrovision rhel8 guest on zcc

README.md
Signed-off-by: wlchurch <wlchurch@hotmail.com>
=> Third times a charm

feilong_meetings/20191212-meeting_notes.md
=> 20191212 Feilong meeting notes

feilong_meetings/20200109-meeting_notes.md
=> 20200109 Feilong meeting notes

zvmsdk/tests/unit/test_dist.py, zvmsdk/tests/unit/test_volumeop.py
push this issue fix to 1.5.n branch.
=> fix unit test issue about volume attach/detach

zthin-parts/zthin/src/rcdescriptions.c, zthin-parts/zthin/src/smcliQuery.c
Query_API_Functional_Level doesn't support z/VM 7.1 now...
=> add 7.1 support for Query_API_Functional_Level

zthin-parts/zthin/bin/refresh_bootmap
Shell script for refresh bootmap. This script has already implement:
1. Refresh boot for RHEL8* zipl
2. Support multi fcp and wwpn.
Example:
./refresh_bootmap.sh --fcpchannel=5d71 --wwpn=0x5005076802400c1a --lun=0x0000000000000000
./refresh_bootmap.sh --fcpchannel=5d71,5d72 --wwpn=0x5005076802400c1a,0x5005076802400c1b --lun=0x0000000000000000
=> Refresh bootmap script

zvmsdk/tests/unit/test_vmops.py
=> fix ut errors

doc/source/errcode.csv, doc/source/restapi.rst, doc/source/zvmsdk.conf.sample, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_vmops.py
=> fix ut errors and doc errors

CONTRIBUTING.md, doc/source/quickstart.rst, setup.py
mfcloud ==> openmainframeproject
=> Migrate to OMP

doc/source/parameters.yaml, doc/source/restapi.rst, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/sdkwsgi/handlers/guest.py, zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/tests/fvt/api_templates/test_guest_deregister.tpl, zvmsdk/tests/fvt/test_utils.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py, zvmsdk/tests/unit/test_api.py
This PR is for master branch and the related PR is https://github.com/openmainframeproject/python-zvm-sdk/pull/61
=> Haoqf dereg master

zthin-parts/zthin/bin/IUCV/iucvserverdaemoninstaller.sh, zvmsdk/networkops.py
Fix selinux errors on rhel8 image.
=> [master]Rhel8 image supports enforcing selinux

zthin-parts/zthin/bin/IUCV/iucvserverdaemoninstaller.sh, zvmsdk/networkops.py
Fix selinux errors on rhel8 image.
=> [1.5.n]Rhel8 image supports enforcing selinux.

zthin-parts/zthin/bin/creatediskimage
This function has been merged into master branch, but i forgot commit it to 1.5.n branch.
=> update creatediskimage scripts to support boot from volume image

feilong_meetings/20200206-meeting-notes.md
Signed-off-by: James Vincent <jamesscottvincent@gmail.com>
=> meeting minutes for feilong 20200206

zthin-parts/scripts/unpackdiskimage, zthin-parts/zthin/bin/unpackdiskimage
Signed-off-by: zhengxiaomei123 <xmzheng@cn.ibm.com>
=> [Master] Support unpackdiskimage to recheck dasdfmt.

zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py
Allow [] for the dedicate_vdevs parameter.
=> [Master] fix the guest_create parameter error

zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py
Allow [] for the dedicate_vdevs parameter.
=> [1.5.n] fix the guest_create parameter error

feilong_meetings/20200220-meeting_notes.md
=> 20200220 Feilong meeting notes

doc/source/parameters.yaml
=> [1.5.n] Add missing params in restapi.rst

doc/source/parameters.yaml, doc/source/restapi.rst, zvmsdk/api.py, zvmsdk/networkops.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_image.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/vmops.py
Update the doc change to support rhcos image
Add disk_type for RHCOS image import
image export also returns comments info
=> [master] RHCOS image import support

doc/source/errcode.csv, doc/source/parameters.yaml, zvmsdk/returncode.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> [1.5.n]Add ignition check and make sure remove it after use

doc/source/parameters.yaml, doc/source/restapi.rst, zvmsdk/api.py, zvmsdk/networkops.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_image.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/vmops.py
Update the doc change to support rhcos image
Add disk_type for RHCOS image import
image export also returns comments info
=> [1.5.n]RHCOS image import support

zvmsdk/tests/unit/test_volumeop.py
fix root volume attach/detach UT error.
=> [Master]fix ut error

zvmsdk/tests/unit/test_volumeop.py
fix root volume attach/detach ut error.
=> [1.5.n]fix ut error

zvmsdk/tests/unit/test_volumeop.py
issue:https://github.ibm.com/zvc/planning/issues/1587
fix test_volumeop.py pep8 error.
=> [Master]fix test_volumeop pep8 error

zvmsdk/tests/unit/test_volumeop.py
issue:https://github.ibm.com/zvc/planning/issues/1587
fix test_volumeop.py pep8 error.
=> [1.5.n]fix test volumeop pep8 error

zvmsdk/tests/fvt/test_volume.py
Fix fvt test_volume.py case pep8 error.
=> [Master]fix fvt test volume case pep8 error

zvmsdk/tests/fvt/test_volume.py
Fix fvt test_volume.py case pep8 error.
=> [1.5.n]fix fvt test volume case pep8 error

doc/source/parameters.yaml, doc/source/restapi.rst, smtLayer/getVM.py, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/hostops.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/host.py, zvmsdk/smtclient.py, zvmsdk/tests/fvt/api_templates/test_host_get_guest_list.tpl, zvmsdk/tests/fvt/test_host.py, zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_host.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_hostops.py, zvmsdk/tests/unit/test_smtclient.py
Add host_get_guest_list interfaces to get all the guests from hypervisor, which is needed by CIC onboarding feature.
=> [Master] add  interfaces to get guests list from the host

zthin-parts/zthin/bin/refresh_bootmap
Also refresh resuce file's bootmap info for RHEL8
=> [1.5.n] Also refresh resuce file's bootmap in RHEL8

doc/source/errcode.csv, smtLayer/getHost.py, smtLayer/tests/unit/test_getHost.py
???? might be returned from SMAPI layer
add a funtion to guess the type from size
as 9336 and 3390 size are very different
=> Add get Host guess size

doc/source/restapi.rst, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/guest.py, zvmsdk/tests/fvt/api_templates/test_guest_get_power_state_real.tpl, zvmsdk/tests/fvt/test_guest.py, zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_api.py
have rebased to the lastest 1.5.n branch, passed all the tox check.
=> [1.5.n] guest get power state real for onboarding

doc/source/restapi.rst, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/guest.py, zvmsdk/tests/fvt/api_templates/test_guest_get_user_direct.tpl, zvmsdk/tests/fvt/test_guest.py, zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_api.py
have rebased to the latest 1.5.n branch and passed all the tox tests.
=> [1.5.n] onboarding guest get user direct

zthin-parts/zthin/bin/unpackdiskimage, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
FCP, WWPN and LUN are required for copying rhcos fcp image
update unpackdiskimage to use FCP, WWPN and LUN to identify the device where the rhcos fcp images will be copied to
=> [master] Update unpackdiskimage to support rhcos fcp image

zthin-parts/zthin/bin/unpackdiskimage, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
FCP, WWPN and LUN are required for copying rhcos fcp image
=> [1.5.n]Update unpackdiskimage to support rhcos fcp image

smtLayer/tests/unit/test_getHost.py
=> [1.5.n] Add 3390-? and 9336-? support

zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
guest_deploy and guest_create_nic
=> [master] Add None schema support for vdev

zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
guest_deploy and guest_create_nic
=> [1.5.n] Add None schema support for vdev

zthin-parts/zthin/bin/unpackdiskimage
=> [master] Remove temp file after unpack is completed

zthin-parts/zthin/bin/unpackdiskimage
=> [1.5.n] Remove temp file after unpack is completed

doc/source/parameters.yaml, doc/source/restapi.rst
Add null support for guest deploy and guest create nic
=> [master] Doc changes

doc/source/parameters.yaml, doc/source/restapi.rst
Add null support for guest deploy and guest create nic
=> [1.5.n] Doc changes

zthin-parts/zthin/src/smcliImage.c
=> Fix 592/0 for Image_Create_DM

feilong_meetings/20200305-meeting_notes.md
=> 20200305 Feilong meeting notes

feilong_meetings/20200319-meeting_notes.md
=> 20200319 Feilong meeting notes

zthin-parts/zthin/bin/unpackdiskimage
=> [master]Remove unused lszdev in unpackdiskimage

zthin-parts/zthin/bin/unpackdiskimage
=> [1.5.n] Remove unused lszdev in unpackdiskimage

zthin-parts/zthin/bin/refresh_bootmap
1. remove unnecessary chroot operation
2. sync cache to disk before umount
3. update mount parameter
4. Fix the rhel8 deploy error by specifying the root partition with multipath disk path
=> [master] update refresh_bootmap tool for several fix&enhancements

feilong_meetings/20200402-meeting_notes.md
=> 20200402 Feilong meeting notes

zthin-parts/zthin/bin/refresh_bootmap
1. refresh_bootmap to use multipath to access disk if multipathd enabled,
otherwise fall back to single path
2. remove several useless and duplicated code
=> [Master] update refresh_bootmap to be able to access disk with multipath

zthin-parts/zthin/bin/unpackdiskimage
Need to check the command return code for rhcos image
and replace log with printError
=> [master] Add error check for RHCOS image

zthin-parts/zthin/bin/unpackdiskimage
Need to check the command return code for rhcos image
and replace log with printError
=> [1.5.n]Add error check for RHCOS image

zthin-parts/zthin/bin/unpackdiskimage
=> refine unpackdiskimage to read GPT partition info

smtLayer/vmUtils.py
linkdiskandbringonline sometimes failed because disks not ready.
So retry it.
=> [Master]Let linkdiskbringonline retry

smtLayer/vmUtils.py
retry linkdiskandbringonline for unready disks
=> [1.5.n]Let linkdiskbringonline retry 1.5.n

zthin-parts/zthin/bin/refresh_bootmap
Register cleanup function to EXIT sigual
=> [master] Add rollback for refresh_bootmap script

zthin-parts/zthin/bin/refresh_bootmap
Register cleanup function to EXIT sigual
=> [1.5.n] Add rollback for refresh_bootmap script

zvmsdk/smtclient.py
1. rename the mount point of swap partition from /mnt/ephemeralxxxx to swap.
=> [Master] Modify the mount point of swap partition in guest.

zvmsdk/smtclient.py
1. rename the mount point of swap partition
=> [1.5.n] modify the mount point of swap partition in fstab file of guest

zthin-parts/zthin/bin/unpackdiskimage
=> [master] Update zipl to add nameserver for rhcos43 support

zthin-parts/zthin/bin/unpackdiskimage
=> Update zipl to add nameserver for rhcos43 support

zthin-parts/zthin/bin/unpackdiskimage
=> [master] Typo error for nameserver in unpackdiskimage

zthin-parts/zthin/bin/unpackdiskimage
=> [1.5.n]Typo error for nameserver in unpackdiskimage

zthin-parts/zthin/bin/unpackdiskimage
=> [master] Fix typo

zthin-parts/zthin/bin/unpackdiskimage
=> [1.5.n] Fix typo

smtLayer/ReqHandle.py
Signed-off-by: haolp <haolp@cn.ibm.com>
=> [1.5.n]print debug level log for smt regardless of the sdk conf setting

feilong_meetings/20200416-meeting_notes.md
=> 20200416 Feilong meeting notes

zvmsdk/config.py
=> [master]change default value of timeout for waiting stop actions

zvmsdk/sdkwsgi/schemas/guest.py
=> [master] Fix the error in guest stop schema

zvmsdk/sdkwsgi/schemas/guest.py
=> [1.5.n] Fix the error in guest stop schema

zthin-parts/zthin/bin/refresh_bootmap
=> [1.5.n]1.5.n remove remaining fcp device

zthin-parts/zthin/bin/unpackdiskimage
=> [master] Fix bug for firstboot remove related to rhcos scsi image

zthin-parts/zthin/bin/unpackdiskimage
=> [1.5.n] Fix bug for firstboot remove related to rhcos scsi image

feilong_meetings/20200514-meeting_notes.md
=> 20200514 Feilong meeting notes

feilong_meetings/20200528-meeting_notes.md
=> 20200528 Feilong meeting notes

zvmsdk/volumeop.py
In the current implementation, the FCP device will be unreserved firstly before executing the smcli undedicate command. 
But in multi-thread case, if one FCP device is set unreserved, maybe other thread will use the same FCP device and then will raise an error.
=> [master] Unreserve a FCP device after undeidcate a FCP device

doc/source/makeimage.rst
=> [master] add doc for rhel81 image

zthin-parts/zthin/bin/unpackdiskimage
use the parted command rather than the `fdasd -a` to divide single partition, this action is same as the multiple partitions'.
=> [master]parted the partition from 64th track rather than 2nd track for sles15 guest

doc/source/quickstart.rst, zthin-parts/Makefile
=> Link libtirpc when build zthin in RHEL8

zvmsdk/dist.py, zvmsdk/networkops.py
@dongyanyang pleasee help to review.
1. change network file path and name;
2. change network apply command in 'get_znetconfig_contents' method;
3. generate a yaml file for network configuration.
4. import a python yaml modue to save a yaml file. --->change to use pyYAML
https://github.ibm.com/zvc/planning/issues/2634
[root@UT zvmsdk]#
pep8: commands succeeded
=> [master]add network support for ubuntu20

data/setupDisk
Make sure the ephemeral and swap disk still exist on sles15 vm after reboot.
=> [master] sles15 supports the ephemeral and swap disk

scripts/zvmsdk-gentoken
correct print(msg) in zvmsdk-gentoken
=> [master]correct print(msg) in zvmsdk-gentoken

zthin-parts/zthin/bin/unpackdiskimage
support sles15 deployment  with fba disk.
=> [master] support sles15 deployment  with fba disk

test-requirements.txt
=> Add yaml as test requirements to be able to build doc

requirements.txt, test-requirements.txt
=> update yaml to 3.10

zthin-parts/zthin/bin/unpackdiskimage
=> [master]zcc supports rhel82 xfs image

.github/workflows/pr.yaml, zvmsdk/networkops.py
* Enable github actions for PEP8/UT/Docs
* Fix a python2 to python3 PEP8 issue
=> [master]Enable PEP8/UT/Docs check use github actions

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> Fix the error about python3 update

.github/workflows/fvt.yaml
FVT Test on Vicom Infinity environment
Signed-off-by: Dong Ma <winterma.dong@gmail.com>
=> [Do Not Merge] FVT on s390x

zvmsdk/vmactions/templates/grow_root_volume.j2
update the template of grow root partition for scsi root disk
so that xfs fs can also be supported
=> support xfs file system for BFV guest

tools/share/zvmguestconfigure
setup iso to loop device only once in the guest vm
=> [master]setup iso to loop device only once in the guest vm

smtLayer/getVM.py
The get console output failed due to python upgrade, need to decide
bytes
=> [master] Get console output error due to python upgrade

zvmsdk/dist.py
@dongyanyang update in ubuntu20 class.
=> [master]correct fcp device file name for ubuntu20

feilong_meetings/20200903-meeting_notes.md
=> 20200903 Feilong meeting notes

feilong_meetings/20200806-meeting_notes.md
=> 20200806 Feilong meeting notes

zthin-parts/zthin/bin/unpackdiskimage
=> Use resizepart option for parted v3

zvmsdk/dist.py
fix sles dns not configured error
=> [master]fix sles dns not configured error

zvmsdk/dist.py
fix the deployment of sles vm when the network without dns.
=> [master]fix deployment of sles when the network without dns

doc/source/errcode.csv, zvmsdk/returncode.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
raise exception when IUCV is unauthorized.
=> [master]raise exception when IUCV is unauthorized

doc/source/makeimage.rst
=> [master]update doc for deleting the resize code when creating image

feilong_meetings/20201001-meeting_notes.md
=> 20201001 Feilong meeting notes

feilong_meetings/20200917-meeting_notes.md
=> 20200917 Feilong meeting notes

GOVERNANCE.md, README.md
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Update z/VM Cloud Connector references to Feilong

doc/source/architecture.rst, doc/source/conf.py, doc/source/errorcodemsg.rst, doc/source/faq.rst, doc/source/generalinfo.rst, doc/source/index.rst, doc/source/makeimage.rst, doc/source/parameters.yaml, doc/source/quickstart.rst, doc/source/restapi.rst, doc/source/sample.rst, doc/source/setuphttpd.rst
=> Rename z/VM cloud connector to Feilong in documentation

feilong_meetings/20201015-meeting_notes.md
=> 20201015 Feilong meeting notes

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
The 72 lines limitation of user direct lead to issue of VLAN 
this PR fixed this issue
=> Avoid 72 line length limitation of user direct

feilong_meetings/20201112-meeting_notes.md
=> 20201112 Feilong meeting notes

feilong_meetings/20201112-meeting_notes.md
Added link to Feilong---Ansible-Module summer intern github repo
=> Update for 20201112 Feilong meeting notes

zthin-parts/zthin/src/IUCV/iucvclient.c, zthin-parts/zthin/src/smapiUtilities.c, zthin-parts/zthin/src/smcliImage.c
=> Remove sudo when it's a root user in zthin layer

feilong_meetings/20201210-meeting_notes.md
=> 20201210 Feilong meeting notes

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> [devel]filter active FCPs when init database

zvmsdk/exception.py, zvmsdk/sdkwsgi/handlers/guest.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
1. get timeout value when handle guest start
2. set retry exception message
=> get timeout value when handle guest start

doc/source/zvmsdk.conf.sample, zvmsdk/api.py, zvmsdk/config.py, zvmsdk/tests/unit/test_api.py
this add an option to control whether swap is created from vdisk or mdisk
=> Add option to control swap disk with vdisk

zthin-parts/zthin/bin/unpackdiskimage
=> flush multipath after disconnectfcp in unpackdiskimage

smtLayer/makeVM.py, smtLayer/msgs.py, smtLayer/tests/unit/test_makeVM.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
Added maximum check for swap disk creation through VDISK 
=> Fix swap maximum number

feilong_meetings/20210107-meeting_notes.md
=> 20210107 Feilong meeting notes

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
found missing need_restart in detach rollback
=> [master]add missing parameter in detach rollback

zthin-parts/zthin/bin/refresh_bootmap, zthin-parts/zthin/bin/unpackdiskimage
=> add debug log for BFV in refresh_bootmap and unpackdiskimage

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/utils.py, zvmsdk/volumeop.py
to support concurrence occasions
=> [master]add lock for volume_refresh_bootmap

zthin-parts/zthin/bin/refresh_bootmap
=> add partprobe before retry getting devNode

doc/source/errcode.csv, zvmsdk/returncode.py, zvmsdk/smtclient.py, zvmsdk/utils.py
=> fix KeyError when refresh_bootmap reach timeout

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> [master]get_from_assigner should return unreserved FCPs

doc/source/errcode.csv, tools/share/zvmguestconfigure, zvmsdk/returncode.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py, zvmsdk/volumeops/templates/rhel7_attach_volume.j2, zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_attach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2
if zvmguestconfigure failed when executing attach/detach scripts, will raise exceptions.
=> [master]add error capture mechanism in zvmguestconfigure

setup.py
=> add missing package data for sles ubuntu template

zvmsdk/dist.py, zvmsdk/tests/unit/test_dist.py, zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2
=> offline fcp devices if detach the last volume

zvmsdk/volumeops/templates/sles_attach_volume.j2, zvmsdk/volumeops/templates/ubuntu_attach_volume.j2
=> add FC connection check for SLES and UBUNTU

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
1. when found a fcp in db but not in current `zvmsdk.conf:fcp_list`: will delete the fcp if it is not reserved(used by any vm)
2. when attach/detach volume to the VM which use the fcp not in current `zvmsdk.conf:fcp_list`, get the wwpn with a smt call again, since the fcp not in conf will not get init and can't get the detail info from current fcp_pool
=> [master]add support to exclude fcp from db if not reserved

setup.py
=> miss rhel8 detach package data

zvmsdk/volumeop.py
=> enhance logs when reporting orphan

smtLayer/getVM.py, smtLayer/tests/unit/test_getVM.py
=> process abnormal output of extract_fcp_info

doc/source/zvmsdk.conf.sample, zvmsdk/config.py
fix document file zvmsdk.conf.sample mismatch with automate generate one by zvmsdk/config.py.
=> fix document mismatch with code

zvmsdk/volumeop.py
=> fix potential bugs

doc/source/parameters.yaml, doc/source/restapi.rst, smtLayer/getHost.py, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/constants.py, zvmsdk/exception.py, zvmsdk/hostops.py, zvmsdk/returncode.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/host.py, zvmsdk/sdkwsgi/schemas/host.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py, zvmsdk/tests/fvt/api_templates/test_host_volume.tpl, zvmsdk/tests/unit/sdkwsgi/handlers/test_host.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_hostops.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/utils.py
=> [master]Add interfaces to get volume info from the host

zvmsdk/exception.py
=> [master]Dev/rxf fix error message get

zthin-parts/zthin/bin/refresh_bootmap
Signed-off-by: flytiger <flytiger@li-746c08c7-c673-e611-bcb0-4ccc6a74036b.ibm.com>
=> if getting map_name failed, call partprobe directly

zthin-parts/zthin/bin/refresh_bootmap
detect and deactivate all volume groups on the root volume before doing the multipath flush
=> update refreshbootmap to support lvm guest

doc/source/parameters.yaml, doc/source/restapi.rst, zvmsdk/sdkwsgi/validation/parameter_types.py
1) doc update
2) a bug fix (min len = 0)
=> update account param

zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
=> permanently remove lun when detach volumes

zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
=> detachment will continue when volume is in-use

smtLayer/makeVM.py, smtLayer/tests/unit/test_makeVM.py
=> add test and make profile/account upper case

zvmsdk/vmops.py
=> reword non-reachable message

zvmsdk/tests/unit/test_vmops.py
=> add unittest for guest_start with timeout

doc/source/zvmsdk.conf.sample, zvmsdk/config.py, zvmsdk/smtclient.py
=> make timeout of executing refresh_bootmap configurable

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> update path value of FCP in database when its value changed

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
comment is None lead to iteration issue
=> Fix comment is None issue

zthin-parts/zthin/bin/refresh_bootmap
remove the dirty data in /etc/zfcp.conf left in image
=> remove dirty data in zfcp.conf

zvmsdk/volumeop.py
=> enhance logs of fcp reserve and unreserve

zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
=> enhance logs in detach scripts

smtLayer/vmUtils.py, zthin-parts/zthin/bin/unpackdiskimage
- Add debug log in deployRHCOSCKDimage
- Flush disk buffer after update zipl
- Flush disk buffer as the last step of smtLayer.vmUtils.installFS
=> Add debug log

zthin-parts/zthin/bin/unpackdiskimage, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
So that we can have more information to debug once there is problem
happened.
=> [master] Add debug log of the image format in guest_deploy

smtLayer/makeVM.py, smtLayer/tests/unit/test_makeVM.py, zvmsdk/api.py, zvmsdk/sdkwsgi/handlers/guest.py, zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/sdkwsgi/validation/parameter_types.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/tests/unit/test_vmops.py, zvmsdk/vmops.py
=> Add support for COMMAND PCIF

smtLayer/makeVM.py, smtLayer/tests/unit/test_makeVM.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> Fix logon by Statement issue

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Signed-off-by: wgxoyun@cn.ibm.com <wgxoyun@cn.ibm.com>
Generate the physical and virtual wwpn map.
=> [master]Generate the physical and virtual wwpn map.

zvmsdk/database.py, zvmsdk/hostops.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_hostops.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> Add fcp info into hostops

zvmsdk/returncode.py, zvmsdk/tests/unit/test_utils.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/utils.py, zvmsdk/volumeop.py
=> use vmcp query to replace smcli to get lpar name

zvmsdk/api.py, zvmsdk/hostops.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_hostops.py
=> [master]Set cache for volumes list of the host

zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/database.py, zvmsdk/hostops.py, zvmsdk/sdkwsgi/handlers/volume.py, zvmsdk/sdkwsgi/schemas/volume.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_hostops.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> refine get_all_fcp_usage

smtLayer/getVM.py, smtLayer/tests/unit/test_getVM.py, zvmsdk/constants.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> optimize calls of System_WWPN_Query

zvmsdk/api.py
=> Skip IUCV authorization when migrating RHCOS guests

zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/sdkwsgi/handlers/volume.py, zvmsdk/sdkwsgi/schemas/volume.py, zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> add raw parameter in get_all_fcp_usage

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> add new columns of wwpn in fcp table

zvmsdk/volumeop.py
=> avoid calling smcli to check fcp status when no fcp_list is configured

zvmsdk/volumeops/templates/rhel7_attach_volume.j2, zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_attach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2, zvmsdk/volumeops/templates/sles_attach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2, zvmsdk/volumeops/templates/ubuntu_attach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
=> append more logs in attach detach scripts

doc/source/quickstart.rst, zvmsdk/version.py
To remind user to add the two new columns into fcp table when
update to 1.6.3 or newer version
=> Update doc for fcp table schema change

smtLayer/smapi.py, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/hostops.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/host.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
Return SSI cluster as a list if host is an SSI cluster member,
otherwise, return [].
=> [master] Add API to query if a host is an SSI cluster member

smtLayer/cmdVM.py, smtLayer/msgs.py, smtLayer/vmUtils.py, zvmsdk/config.py, zvmsdk/smtclient.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> add timeout for execution of punch script

zvmsdk/database.py, zvmsdk/volumeop.py
https://github.ibm.com/zvc/planning/issues/8141
=> [master]change log level from error to warning when no record in fcp db

zvmsdk/database.py
remove the log from this method, because other method which call this method will log message
=> [master]remove the log when no fcps found in db

doc/source/errcode.csv, doc/source/zvmsdk.conf.sample
=> add config sample for punch_script_timeout

zvmsdk/volumeop.py
=> change error messages of attach failure

doc/source/parameters.yaml, doc/source/restapi.rst, zvmsdk/tests/fvt/api_templates/test_host_ssi_info.tpl
=> [master]Update doc for new added  API to get host ssi cluster info

zthin-parts/Makefile, zthin-parts/zthin/include/smcliSystem.h, zthin-parts/zthin/include/vmapiSystem.h, zthin-parts/zthin/src/smcli.c, zthin-parts/zthin/src/smcliSystem.c, zthin-parts/zthin/src/vmapiSystemProcessorQuery.c
=> add new smcli System_Processor_Query

zvmsdk/volumeop.py
=> remove unnecessary logs when fcp notfound in db

doc/source/errcode.csv, smtLayer/msgs.py, smtLayer/powerVM.py, smtLayer/vmUtils.py
So that it won't hang forever.
Conflicts:
smtLayer/vmUtils.py
=> [master] Add timeout for poweroff and restart VM

tox.ini
Remove test db in tox run scripts
=> Remove test db in tox run scripts

zvmsdk/database.py, zvmsdk/volumeop.py
=> add news tables to support FCP templates

smtLayer/getHost.py, smtLayer/tests/unit/test_getHost.py
Fix cpu total and cpu used number error in mixed CP+IFL env.
Get result from smcli to override the result from "cat /proc/sysinfo".
=> Fix mixed CP+IFL cpu_total and cpu_used from smcli 

zvmsdk/database.py, zvmsdk/volumeop.py
=> set connections and reserved to 0

zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/database.py, zvmsdk/exception.py, zvmsdk/returncode.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/volume.py, zvmsdk/sdkwsgi/schemas/volume.py, zvmsdk/volumeop.py
=> add API to create a FCP template

zvmsdk/api.py, zvmsdk/database.py, zvmsdk/volumeop.py
Update API return examples in below comments.
below are the two main method for two APIs in file `zvmsdk/volumeop.py `:
```python
def get_fcp_templates(self, template_id_list=None, filters=None):
"""Get template base info
:param template_list: (list) a list of template id, if it is None,  get all the templates on the host
filtered with the specified filters
:filters: {dict}, keys can be assigner_id, host_default and sp_default
{
"assigner_id": (str)
"host_default" : "Y" or "N",
"sp_default": ["All" or sp1, sp2, ...]
}
"""
```
```python
def get_fcp_templates_detail(self, template_list=None, raw=False, statistics=True, sync_with_zvm=False):
```
=> update for list fcp tempate API

zvmconnector/restclient.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/volume.py, zvmsdk/sdkwsgi/schemas/volume.py, zvmsdk/sdkwsgi/validation/parameter_types.py
```
>>> con.send_request('get_fcp_templates',template_id_list=['36439338-db14-11ec-bb41-0201018b1dd2','12345678'])
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': 
{
'fcp_templates': [
{'id': '12345678', 'name': 'templatet1', 
'description': 'test1', 'is_default': 0, 
'sp_name': ['sp3']
}, 
{'id': '36439338-db14-11ec-bb41-0201018b1dd2', 
'name': 'default_template', 'description': 'This is Default template', 
'is_default': 1, 
'sp_name': ['v7k60', 'sp4']
}
]
}}
```
```
>>> pp(con.send_request('get_fcp_templates',default_sp_list=['v7k60','sp3']))
{'errmsg': '',
'modID': None,
'output': {'fcp_templates': [{'description': 'This is Default template',
'id': '36439338-db14-11ec-bb41-0201018b1dd2',
'is_default': 1,
'name': 'default_template',
'sp_name': ['v7k60']}, …
```
=> sdkwsgi update for list fcp tempate API

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> add 596/396 info

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> add SMAPI error handle

smtLayer/tests/unit/test_vmStatus.py, smtLayer/vmStatus.py
=> Add status for SMAPI calls

zvmsdk/dist.py, zvmsdk/tests/unit/test_dist.py
Add code logic to parse MTU value from network info
and set to network configuration scripts for SLES and Ubuntu.
=> [master]Add MTU suport for SLES and Ubuntu

doc/source/parameters.yaml, doc/source/restapi.rst
=> [master] Add doc for the 3 new returned values in guest_get_info

zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_database.py
=> add missing UT cases in restclient and sdkwsgi

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
=> update codes because return value of get_fcp_usage changed

smtLayer/tests/unit/test_vmStatus.py, smtLayer/vmStatus.py, smtLayer/vmUtils.py
Add lock for vmstatus operations to make thread safe for record success/fail (writer action)
=> Add lock for vm status operations

zvmsdk/api.py, zvmsdk/database.py, zvmsdk/sdkwsgi/handlers/volume.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py, zvmsdk/tests/unit/sdkwsgi/test_handler.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
```
_______________________________________________________ summary _______________________________________________________
pep8: commands succeeded
(venv3) [root@fba82 zvmsdk]#
```
=> [master]fix issue when get not host default fcp template

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
In this PR:
1. move acquire lock out of try-catch
2. update a method name in _rollback_dedicated_fcp
=> bug fix - update method name from unreserve to unreserve_fcps

zthin-parts/zthin/bin/IUCV/iucvserverdaemoninstaller.sh, zvmsdk/dist.py, zvmsdk/sdkwsgi/validation/parameter_types.py
Signed-off-by: qpqi <qpqi@cn.ibm.com>
This PR is developed for adding vm deployment support for rhel9.
=> add rhel9 support

zvmsdk/smtclient.py, zvmsdk/tests/unit/test_smtclient.py
=> handle 596/6831 error by retry delete user again

zvmsdk/sdkwsgi/requestlog.py, zvmsdk/sdkwsgi/util.py, zvmsdk/tests/unit/sdkwsgi/test_utils.py
issue: https://github.ibm.com/zvc/planning/issues/10674
Signed-off-by: wngzhe <wngzhe@cn.ibm.com>
passut and pep8
Signed-off-by: wngzhe <wngzhe@cn.ibm.com>
=> mask X-Auth-Token in log with secret like ***

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/utils.py, zvmsdk/volumeop.py
The PR do the following:
1. enhance rollback for volume attach and detach
2. when detaching volume, if removing volume from VM OS succeeds, then try best to undedicate every FCP device from the z/VM
3. remove used methods
=> [master] enhance_volume_attach_detach_rollback

setup.py, zvmsdk/version.py
=> update version to 1.6.4

zvmsdk/sdkserver.py
=> Add logs for sdkserver down

zvmsdk/version.py
=> next version should be 1.6.5

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Solve the problems that:
1. the scope of lock in do_attach is too big, sometimes it will block other DB operations
2. move add_disks and remove_disks out of scope of lock, because they might take a long time, in case it block other opations.
=> try to refine do_attach and do_detach

zvmsdk/sdkwsgi/validation/parameter_types.py
=> add parameter of fcp_template_id in connection_info

zvmsdk/volumeop.py, zvmsdk/volumeops/templates/rhel7_detach_volume.j2, zvmsdk/volumeops/templates/rhel8_detach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
=> continue to do unit_remove if no WWID found

smtLayer/getVM.py
=> When no fcp devices in zvm, smcli should return empty

.github/workflows/pr.yaml, tox.ini
Run py36 on ubuntu-18.04
Run py37 on ubuntu-latest
Signed-off-by: Dong Ma <winterma.dong@gmail.com>
=> Update the github action run both py36 and py37

zvmsdk/volumeop.py
remove the unnecessary _LOCK_RESERVE_FCP
=> remove the unnecessary _LOCK_RESERVE_FCP

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Enhance error msg when deploy a bfv with fcp device template not exist
Signed-off-by: PEI REN <renpei@cn.ibm.com>
=> Enhance error msg when deploy a bfv with fcp device template not exist

smtLayer/tests/unit/test_getVM.py
add UT for PR : https://github.com/openmainframeproject/feilong/pull/699
=> add UT for pr 699

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
https://github.ibm.com/zvc/planning/issues/11877
Without the fix,
check condition is different between _rollback_dedicated_fcp_devices and _do_attach.
It causes that _rollback_dedicated_fcp_devices does NOT actually do the undedication.
The PR fix the issue by use the same check condition between _rollback_dedicated_fcp_devices and _do_attach.
=> _rollback_dedicated_fcp_devices does not take into effect

zvmsdk/volumeops/templates/ubuntu_attach_volume.j2, zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
fix the bug that the device path format is not correct in ubuntu attach detach script
=> fix the wrong disk path bug in attach detach bugs

zvmsdk/volumeops/templates/rhel8_attach_volume.j2, zvmsdk/volumeops/templates/sles_attach_volume.j2, zvmsdk/volumeops/templates/sles_detach_volume.j2
I missed to change this in previous commits.
=> change chccwdev to chzdev when online fcp devices

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_utils.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/utils.py, zvmsdk/volumeop.py
Update FCP table schema and sync the PCHID info into FCP database
=> Update FCP table schema and sync the PCHID info into FCP database

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py
Provide a function to return pchids of an FCP template
=> Provide a function to return pchids of an FCP template

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Signed-off-by: wngzhe <wngzhe@cn.ibm.com>
1. add key pchids, cpc_sn,cpc_name and lpar to the return value of create_fcp_template/edit_fcp_template
2. pass ut
=> [master] add key in return values for create_fcp_template/edit_fcp_template

zvmsdk/database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
code change: add hypervisor_hostname to return value of edit/ceate_fcp_template and match comments
=> [master ] add hypervisor_hostname to return value of edit/ceate_fcp_template and match comments

zvmsdk/database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Update the API of get_fcp_template_details and get_fcp_templates to return the CPC/LPAR/PCHID info
=> Update the API of get_fcp_template_details and get_fcp_templates to return the CPC/LPAR/PCHID info

zvmsdk/tests/unit/test_api.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Only print pchid info when sdkserver is starting
=> Only print pchid info when sdkserver is starting

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Fix the issue of get incorrect pchids list when get_fcp_templates_detail
=> Fix the issue of get incorrect pchids list when get_fcp_templates_detail

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Change pchid/chpid to case insensitive in ZCC API response
=> Change pchid/chpid to case insensitive in ZCC API response

zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
Remove the duplicated pchid record among multiple paths of one fcp_template
=> Remove the duplicated pchid record among multiple paths of one fcp_template

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
code change： Modify the returned data structure when create/edit fcp template ， change item in return dict  change 'add' from list to a dict
'add' : {
'add': ['A', 'B'],
'first_used_by_templates': ['C']
},
Signed-off-by: wngzhe <wngzhe@cn.ibm.com>
pass ut
=> [master]  Modify the returned data structure when create/edit fcp template

scripts/tests/unit/base.py, scripts/tests/unit/test_zvmsdk-getpchid.py, scripts/zvmsdk-getpchid, zvmsdk/database.py, zvmsdk/tests/unit/test_database.py
1. Print PCHIDs ordered by PCHID No.
2. Add UT for tool script /usr/bin/zvmsdk-getpchid
=> Add UT for tool script /usr/bin/zvmsdk-getpchid

zthin-parts/zthin/bin/unpackdiskimage
In case the target disk is zfs filesystem or has other filesystems on it.
=> Add wipefs before dd image to the target disk

zvmsdk/tests/unit/test_vmops.py, zvmsdk/vmops.py
As no IUCV server in RHCOS image.
Sign-off-by: Meng.Jie.Min@ibm.com
=> remove iucv check for rhcos vm

zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py
code change: 1. add ut case for db  function create_fcp_template and edit_fcp_template
=> [master] add unit test scenario for db create and edit fcp template.

zvmsdk/database.py, zvmsdk/volumeop.py
Benefits: more explicit, reduce human error
=> replace index access with dict access of sqlite3.Row object

zvmsdk/database.py, zvmsdk/tests/unit/test_database.py, zvmsdk/tests/unit/test_volumeop.py, zvmsdk/volumeop.py
empty_fcp_list_reason: a str of why fcp_list is empty when allocating FCP device
include empty_fcp_list_reason in the connector returned by get_volume_connector
=> return_empty_fcp_list_reason_in_get_volume_connector

zvmsdk/database.py
I am so sorry that the updated code was not commit by mistack per the comment https://github.com/openmainframeproject/feilong/pull/763/files#r1365118099. 
Fix it in this PR.
=> Update the min value of count_per_path

zvmsdk/monitor.py, zvmsdk/tests/unit/test_monitor.py
Signed-off-by: Rajat Sharma rajat.sharma12@ibm.com
=> Adding logic to fetch memory util with free command.

zvmsdk/monitor.py, zvmsdk/tests/unit/test_monitor.py
Reverts openmainframeproject/feilong#760
=> Revert "Adding logic to fetch memory util with free command."

doc/source/parameters.yaml, doc/source/restapi.rst, smtLayer/tests/unit/test_vmStatus.py, smtLayer/vmStatus.py, zvmsdk/tests/fvt/api_templates/test_smapi_health.tpl
Fixing https://github.com/openmainframeproject/feilong/issues/774
=> fix some doc issues

doc/source/sample.rst
* fix English grammar of existing text
* added one curl example and one python example
Note: I do not know how to regenerate the documentation, so I was not able to check the resulting HTML page.
=> Doc: fix "samples" page

smtLayer/vmStatus.py, zvmsdk/tests/fvt/api_templates/test_smapi_health.tpl
Follow-up of dde3d30f6759aa050fc09e5ad569f8e139a5c6fc
(2 forgotten occurrences)
=> continueous -> continuous

doc/source/architecture.rst, doc/source/generalinfo.rst
General info:
* Mostly updated the links.
* Note: if launchpad is not used anymore for questions and bugs, then the section about reporting bugs should also be reworked. As I did not have the info, I did not touch that.
Architecture:
* Rephrasing
* ~Added example of integration with terraform (with new schema)~
=> Doc: proofread "general info" and "architecture" chapters

GOVERNANCE.md, README.md, doc/source/makeimage.rst, doc/source/parameters.yaml, doc/source/restapi.rst, doc/source/zvmsdk.conf.sample, zvmsdk/api.py, zvmsdk/config.py, zvmsdk/database.py
=> Fix various typos

doc/source/parameters.yaml, doc/source/restapi.rst, zvmconnector/restclient.py, zvmsdk/api.py, zvmsdk/networkops.py, zvmsdk/sdkwsgi/handler.py, zvmsdk/sdkwsgi/handlers/vswitch.py, zvmsdk/smtclient.py, zvmsdk/tests/fvt/api_templates/test_get_switch_record.tpl, zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
code change:
Add active parameter when  detach interface
and change unittest
=> Add detach interface calling active parameter

zvmconnector/restclient.py, zvmsdk/sdkwsgi/schemas/guest.py, zvmsdk/tests/unit/sdkclientcases/test_restclient.py, zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
Change active back to be optional
=> [master]Change active to be optional

data/zvmsdk-wsgi.service, setup.py
A uwsgi.service file added under /lib/systemd/system for starting feilong in uwsgi
=> Add uwsgi service file 

doc/source/setuphttpd.rst
Reorganised sections and subsections of setting up webserver docs
=> Reorganize Web server setup docs

data/zvmsdk.conf, setup.py
Added a configuration file `data/zvmsdk.conf` to improve automating packaging.
=> Configuration file for zvmsdk

doc/source/setuphttpd.rst
Added installation instructions for the RHEL package.
=> Package installation doc for setting up web server 

zvmsdk/sdkwsgi/validation/parameter_types.py
To Support CPU share in case " https://github.ibm.com/zvc/planning/issues/18693 " 
--signed off : ssanthosh@in.ibm.com
=> Added support for custom cpu share

doc/source/quickstart.rst
=> Updated Installation Docs for Deb Packaging

doc/source/quickstart.rst
Remove reference to Aazam's home project
=> Remove reference to Aazam's home project

doc/source/quickstart.rst
=> Align sudoers file name with the packaged one

doc/source/conf.py
This PR produces the following copyright mentions:
```
build/html/quickstart.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/faq.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/configuration.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/change.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/index.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/architecture.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/generalinfo.html:        &#169; Copyright 2017 IBM and 2025 Contributors to Feilong project.
build/html/genindex.html: …
```
=> Documentation also copyright the Feilong contributors

zvmsdk/smtclient.py
Minor fix for VM restart(soft and/or hard) after replacing the undocumented API.
=> Fix for undocumented API replacement
