- zvmsdk/smutclient.py
Fixed images POST:
"errmsg": "Unexpected internal error in ZVM SDK, error: (127.0.0.1:57244) SDK server got unexpected exception: AttributeError(\"'Logger' object has no attribute 'err'\",)",
> LOG.err changed to LOG.error

- smtLayer/vmUtils.py
> Fix the error of dasdfmt

- zthin-parts/zthin/src/smcli.c
- zthin-parts/zthin/src/smcliImage.c
- zthin-parts/zthin/src/smcliImageDefinition.c
- zthin-parts/zthin/src/smcliSystem.c
- zthin-parts/zthin/src/smcliVirtual.c
the target ID should be "" instead of " "or it lead to blank image ID usage..
> Fix RACF support bug

- CODE_OF_CONDUCT.md
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
> Add Code of Conduct ( aligns with OMP standard )

- zvmsdk/dist.py
- zvmsdk/tests/unit/test_dist.py
This commit is related to issue:
https://github.ibm.com/zvc/planning/issues/591
This issues reports a problem, if DNS nameserver info
is specified when creating a network in icic, we expect
it takes effect inside VMs created using this network.
While currently DNS nameserver info is not written to
/etc/resolv.conf.
There are 2 reasons causing problem above:
1. nova zvm driver doesn't read DNS info from openstack
subnet.
2. /etc/resolv.conf probably is overwritten by NetworkManager
due to the latter's working behavior. Need find a way
align with NetworkManager to set the DNS nameserver.
This commit is to solve the 2nd problem. For Rhel,
NetworkManger can read DNS1, DNS2 value from
/etc/sysconfig/network-scripts/ifcfg-enccw0.0.1000 file
and write to /etc/resolv.conf
So this commit is to …
> Write DNS info to network conf file for rhel

- zvmsdk/database.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Now we can attach multipath FCPs to one instance,
But!! we only support multipath, multipath=True is hard coded and
the format of fcp_list configuration should be strict, looks like:
"1111-1115;2111-2115;3111-3115;...."
UT cases were added for those codes.
> support multipath with multipath FCP devices

- zvmsdk/config.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
when capturing multiple VMs, zcc may report error like:
The specified source system is currently running
add an option --wait in guest_softstop function
this option will trigger the wait_for_state logic in smtLayer
and the command will wait until the vm is in shutdown status.
> fix bug of capture failure

- zvmsdk/api.py
When neutron-zvm-agent try to unbind port and revoke
user from vswitch, it calls vswitch_revoke_user in
zvmsdk api.py. Before this method there is a decrator
check_guest_exist to check the userid in db. If the
userid has been deleted from db, vswitch_revoker_user
would fail with error:Guest XXXX does not exist.
This commit is to fix the error by deleting the decrator
because vswitch_revoke_user doesn't require guest exist.
> Fix vswitch_revoker_user error

- zthin-parts/zthin/bin/unpackdiskimage
The new deployed RHCOS vm reboot failed because the zipl bootloader is updated during the initramfs boot process.
This commit is to fix the error by updating the BootLoaderSpec file to have the target zipl parameters.
Signed-off-by: XiaoMeiZheng <xmzheng@cn.ibm.com>
> Fix reboot error of RHCOS created by unpackdiskimage

- zthin-parts/zthin/bin/unpackdiskimage
when resizing the dasd, the "fdasd -a" fails to re-read the partition
table with the BLKRRPART IOCTL error(rc:255). Since the fdasd has already
created the partition and updated the VTOC to the disk, so re-read the
partition table to read the device information.
> Bugfix: fdasd fails to re-read the partition when resizing the dasd.

- zvmsdk/utils.py
If userid is shorter than 5, then check_userid_exist will
return True even the userid doesn't exist at all.
This commit also adds an argument for checking that if
the userid needs logon or not.
> Fix the bug of check_userid_exist

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/fvt/api_templates/test_guest_deregister.tpl
- zvmsdk/tests/fvt/test_utils.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
The VM still exists after deregistered, but its record is
removed from zCC. This is typically used by user to dismiss/offboard
a VM when he doesn't want to manage it through zCC.
nova virt zvm driver should call this API to unmanage a VM with userid,
e.g. in hypervisor.py and driver.py.
> Add guest_deregister in zCC for unmanaging VM

- zvmsdk/tests/unit/test_dist.py
- zvmsdk/tests/unit/test_volumeop.py
Use jinjia2 template shell scripts to achieve volume attach/detach, so the test scripts do not need all assert calls.
> fix unit test issue about volume attach/detach

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/makeVM.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
add two new parameter to guest_create:
dedicate_vdevs: used to dedicate devices like fcp;
loaddev: used to add the loaddev portname and lun statement in the guest definition
> update guest_create API to support boot from volume

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/makeVM.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
add two new parameter to guest_create:
dedicate_vdevs: used to dedicate devices like fcp;
loaddev: used to add the loaddev portname and lun statement in the guest definition
> [1.5.n] update guest_create API to support boot from volume

- zvmsdk/dist.py
- zvmsdk/networkops.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_dist.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/vmops.py
Dhcp can't be used in CoreOS, so a parameter(in form of ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:none[:[<dns1>][:<dns2>]]) are used to tell
unpackdiskimage/dracut create a CoreOS vm with fixed ip and hostname
instead of using "ip=dhcp".
Refer to http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html
> CoreOS fixed IP and hostname support

- zvmsdk/dist.py
- zvmsdk/networkops.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_dist.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/vmops.py
Add CoreOS image support and distro support.
Dhcp can't be used in CoreOS, so a parameter(in form of ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:none[:[<dns1>][:<dns2>]]) are used to tell
unpackdiskimage/dracut create a CoreOS vm with fixed ip and hostname
instead of using "ip=dhcp".
Refer to http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html
Signed-off-by: gyohuangxin <gyo5huang@gmail.com>
add CoreOS support in CIC
> add CoreOS support in CIC

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/returncode.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
add timestamp info to support manage_image_cache API in nova ZVM driver
> [1.5.n]Add time stamp in image query

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
In smtclient.image_get_os_distro and smtclient._get_image_disk_type, image_query
is changed to ImageDbOperator.image_query_record to improve efficiency.
> [master] Update image_get_os_distro and _get_image_disk_type

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
In smtclient.image_get_os_distro and smtclient._get_image_disk_type, image_query
is changed to ImageDbOperator.image_query_record to improve efficiency.
Signed-off-by: gyohuangxin <gyo5huang@gmail.com>
> [1.5.n] Update image_get_os_distro and _get_image_disk_type

- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
add a new parameter skipDD as when boot_from_volume we won't rely
on unpackdiskimage to do DD.
when skipDD is False, image_name is the name of image as original.
when True, image_name will be used as the os_version which will be
used to update the guest database table.
> [master] update guest_deploy to support boot from volume

- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
add a new parameter skipdiskcopy as when boot_from_volume we won't rely
on unpackdiskimage to do disk copy.
when skipdiskcopy is False, image_name is the name of image as original.
when True, image_name will be used as the os_version which will be
used to update the guest database table.
> [1.5.n] update guest_deploy to support boot from volume

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_database.py
The current guest_register API in zCC is originated live migration actually and
it can't fulfill the requirement of onboarding although it intends to.
This PR is to retrofit it to be a general API which can fulfill both migration and onboarding's
requirement, and even future requirements as well.
This PR is for master branch and the related PR is https://github.com/openmainframeproject/python-zvm-sdk/pull/65
> [Master] Provide the VM onboarding function in guest_register API

- zthin-parts/zthin/lib/zthinshellutils
Currently, zthinlog always displays "set device offline failed".
This log should check parameter when displaying log info, etc "online"
or "offline".
> [master]Fix log error info in zthinshellutils

- zthin-parts/zthin/lib/zthinshellutils
Currently, zthinlog always displays "set device offline failed".
This log should check parameter when displaying log info, etc "online"
or "offline".
> [1.5.n] Fix error info in zthinshellutils

- zthin-parts/scripts/unpackdiskimage
- zthin-parts/zthin/bin/unpackdiskimage
With the compatible disk layout, a DASD can have up to three partitions that can be accessed by traditional mainframe operating systems.The RHCOS system need the DASD device with CDL format.
This patch support to check the DASD device be formatted with CDL layout.The check is combined with the check for block_per_tracks.
> [Master] Support unpackdiskimage to check the dasd layout with CDL.

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
This patch does the following things:
1. Parse 'lsluns' command output if not specific wwpns in command line
2. More details info output
3. Change the return info, use "WWPNs" instead of "Physical WWPN"
4. Fix "rd.zfcp=" error. Add "0x" prefix to each wwpn in "rd.zfcp=" option
> [1.5.n] Optimize Refresh bootmap script

- zthin-parts/scripts/unpackdiskimage
- zthin-parts/zthin/bin/unpackdiskimage
For unpackdiskimage script, the multiline cat command (with EOF delimiter/HERE document) sometime failed with output:
cat: -: No such file or directory
It seems to be some permissions issues, but not occur all the time.
This patch create the file at first and the cat multiline to file to solve this error.
> [Master]Patch unpackdiskimage to resolve 'cat' commond failure.

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_database.py
The current guest_register API in zCC is originated live migration actually and
it can't fulfill the requirement of onboarding although it intends to.
This PR is to retrofit it to be a general API which can fulfill both migration and onboarding's
requirement, and even future requirements as well.
This PR is for 1.5.n branch and the related PRs are https://github.com/openmainframeproject/python-zvm-sdk/pull/76 and https://github.com/openmainframeproject/python-zvm-sdk/pull/128
> [1.5.n] Provide the VM onboarding function in guest_register API

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/fvt/api_templates/test_volume_attach_detach.tpl
- zvmsdk/tests/fvt/test_volume.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
This PR is used to update FCP table record about  FCP allocation when create an instance that boot from volume. We can only create one instance on the same compute host if we don't record instance's FCP allocation.
> [Master]support bootable volume attach

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/fvt/api_templates/test_volume_attach_detach.tpl
- zvmsdk/tests/fvt/test_volume.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
This PR is used to update FCP table record about FCP allocation when create an instance that boot from volume. We can only create one instance on the same compute host if we don't record instance's FCP allocation.
> [1.5.n] support bootable volume attach

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/getVM.py
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/hostops.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/host.py
- zvmsdk/smtclient.py
- zvmsdk/tests/fvt/api_templates/test_host_get_guest_list.tpl
- zvmsdk/tests/fvt/test_host.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_host.py
- zvmsdk/tests/unit/sdkwsgi/test_handler.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_hostops.py
- zvmsdk/tests/unit/test_smtclient.py
Add interfaces to get guest list from hypervisor directly
The HTML pages are in doc/build/html.
________________________________________________________________ summary ________________________________________________________________
ERROR:   pep8: commands failed
pep8 error not related to this commit:
[20452] /root/repo/python-zvm-sdk$ /root/repo/python-zvm-sdk/.tox/pep8/bin/flake8
./get-pip.py:90:5: E306 expected 1 blank line before a nested definition, found 0
./env/bin/activate_this.py:6:80: E501 line too long (97 > 79 characters)
./env/bin/activate_this.py:15:80: E501 line too long (95 > 79 characters)
./env/bin/activate_this.py:18:80: E501 line too long (103 > 79 characters)
./env/bin/activate_this.py:21:80: …
> [1.5.n] add host get guests list interfaces for onboarding

- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/restapi.rst
- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/bin/unpackdiskimage
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/vmops.py
- zvmsdk/volumeop.py
1. Update volume_refrsh_bootmap, support to skip zipl update,
only return online wwpn
2. For rhcos FCP support, allow boot from volume, skip copy disk
in unpackdiskimage
> [master] RHCOS FCP support, able to boot from volume

- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/restapi.rst
- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/bin/unpackdiskimage
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/vmops.py
- zvmsdk/volumeop.py
1. Update volume_refrsh_bootmap, support to skip zipl update,
only return online wwpn
2. For rhcos FCP support, allow boot from volume, skip copy disk
in unpackdiskimage
> [1.5.n] RHCOS FCP support, able to boot from volume

- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/tests/fvt/api_templates/test_guest_get_power_state_real.tpl
- zvmsdk/tests/fvt/test_guest.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/sdkwsgi/test_handler.py
- zvmsdk/tests/unit/test_api.py
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
the pep8 error is not related to this commit
./get-pip.py:90:5: E306 expected 1 blank line before a nested definition, found 0
./env/bin/activate_this.py:6:80: E501 line too long (97 > 79 characters)
./env/bin/activate_this.py:15:80: E501 line too long (95 > 79 characters)
./env/bin/activate_this.py:18:80: E501 line too long (103 > 79 characters)
./env/bin/activate_this.py:21:80: E501 line too long (94 > 79 characters)
./env/bin/activate_this.py:26:80: E501 line too long (95 > 79 characters)
./env/lib64/python2.7/os.py:24:1: E265 block comment should start with '# '
> [master] add interfaces to get guest power state from hypervisor

- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/tests/fvt/api_templates/test_guest_get_user_direct.tpl
- zvmsdk/tests/fvt/test_guest.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/sdkwsgi/test_handler.py
- zvmsdk/tests/unit/test_api.py
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
pep8 error not related to this commit:
21392] /root/repo/python-zvm-sdk$ /root/repo/python-zvm-sdk/.tox/pep8/bin/flake8
./get-pip.py:90:5: E306 expected 1 blank line before a nested definition, found 0
./env/bin/activate_this.py:6:80: E501 line too long (97 > 79 characters)
./env/bin/activate_this.py:15:80: E501 line too long (95 > 79 characters)
./env/bin/activate_this.py:18:80: E501 line too long (103 > 79 characters)
./env/bin/activate_this.py:21:80: E501 line too long (94 > 79 characters)
./env/bin/activate_this.py:26:80: E501 line too long (95 > 79 characters)
./env/lib64/python2.7/os.py:24:1: E265 …
> [master] guest get user direct from hypervisor for onboarding

- zthin-parts/zthin/bin/refresh_bootmap
1. remove unnecessary chroot operation
2. sync cache to disk before umount
3. update mount parameter
4. Fix the rhel8 deploy error by specifying the root partition with multipath disk path
> [1.5.n] update refresh_bootmap tool for several fix&enhancements

- zvmsdk/database.py
'FCP' module id is not defined, should use 'volume'. Otherwise when exception happens, it would cause keyerror of 'FCP' and the exception msg would be confusing.
```
2020-03-20 04:07:06.707 23609 ERROR nova.virt.zvm.utils [req-5ddf32d8-50c3-4e83-aa2e-4fa248f611b9 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 f5bd1af496f04678be0a28248af984c5 - default default] zVM Cloud Connector request volume_detach failed with parameters: ({'mount_point': u'/dev/vda', 'assigner_id': 'ydy00038', 'is_root_volume': True, 'os_version': u'Rhel8.1', 'zvm_fcp': [u'5c42', u'5d42'], 'target_lun': '0x0001000000000000', 'multipath': 'true', 'target_wwpn': [u'0x5005076802100C1B', u'0x5005076802200C1B', u'0x5005076802300C1B', u'0x5005076802400C1B', u'0x5005076802400C1A', u'0x5005076802300C1A', …
```
> fix the keyerror exception in fcp database operation

- zvmsdk/database.py
'FCP' module id is not defined, should use 'volume'. Otherwise when exception happens, it would cause keyerror of 'FCP' and the exception msg would be confusing.
```
2020-03-20 04:07:06.707 23609 ERROR nova.virt.zvm.utils [req-5ddf32d8-50c3-4e83-aa2e-4fa248f611b9 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 f5bd1af496f04678be0a28248af984c5 - default default] zVM Cloud Connector request volume_detach failed with parameters: ({'mount_point': u'/dev/vda', 'assigner_id': 'ydy00038', 'is_root_volume': True, 'os_version': u'Rhel8.1', 'zvm_fcp': [u'5c42', u'5d42'], 'target_lun': '0x0001000000000000', 'multipath': 'true', 'target_wwpn': [u'0x5005076802100C1B', u'0x5005076802200C1B', u'0x5005076802300C1B', u'0x5005076802400C1B', u'0x5005076802400C1A', u'0x5005076802300C1A', …
```
> [1.5.n] fix the keyerror exception in fcp database operation

- zthin-parts/zthin/bin/refresh_bootmap
1. refresh_bootmap to use multipath to access disk if multipathd enabled,
otherwise fall back to single path
2. remove several useless and duplicated code
> [1.5.n] update refresh_bootmap to be able to access disk with multipath

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/dist.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/fvt/api_templates/test_guest_grow_root_volume_req.tpl
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmactions/templates/grow_root_volume.j2
- zvmsdk/vmops.py
we cann't rely on cloud-init to extend root partition when the partition is on a multipath disk. So add a new API in this PR to do the extention of guest root volume, by punching a script to the target guest.
> [master] add api to extend root partition of  volume

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/dist.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/fvt/api_templates/test_guest_grow_root_volume_req.tpl
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmactions/templates/grow_root_volume.j2
- zvmsdk/vmops.py
Cann't rely on cloud-init to grow partition and resizefs when the root
partition is on multipath disk.
So add a new API to punch script filt to guest to do the partition grow.
> [1.5.n] add api to extend root partition of  volume

- zthin-parts/zthin/bin/unpackdiskimage
In rhel7, the fdisk(version 2.23) not able get GPT partition info
from RHCOS43 image file. In this change will utilize hexdump to
get the GPT partition info.
> Be able to read GPT partition info from RHCOS43 dasd image

- zvmsdk/utils.py
When the guest is in force pending status, check_userid_exists should return true.
(Error scenario:
guest_shutdown
then detach_volume would check whether the guest exist.
if not handled, the detach_volume would return exception.)
> [Master] fix the check_userid_exists util function to handle the force pending state

- zvmsdk/utils.py
When the guest is in force pending status, check_userid_exists should return true.
(Error scenario:
guest_shutdown
then detach_volume would check whether the guest exist.
if not handled, the detach_volume would return exception.)
> [1.5.n] fix the check_userid_exists util function to handle the force pending state

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Reserve and unreserve FCP devices when deplying and deleting VMs.
> [1.5.n] Reserve FCP devices when deploying VMs

- zvmsdk/database.py
when the fcp connections is already 0 and then detach_volume is called again,
exception.SDKObjectNotExistError error should be raised and returned to the zcc caller
instead of SDKGuestOperationError.
so that the caller layer can check the error and ignore as needed.
> [master] make the fcp exception more accurate

- zvmsdk/database.py
when the fcp connections is already 0 and then detach_volume is called again,
exception.SDKObjectNotExistError error should be raised and returned to the zcc caller
instead of SDKGuestOperationError.
so that the caller layer can check the error and ignore as needed.
> [1.5.n] make the fcp exception more accurate

- setup.py
find_package will by default ignore the vmactions/templates folder
add the files into package_data so that the templates will be installed
> [Master] update setup.py to include template file into the pkg

- setup.py
find_package will by default ignore the vmactions/templates folder
add the files into package_data so that the templates will be installed
> [1.5.n] update setup.py to include template file into the pkg

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
- zvmsdk/smtclient.py
If a FCP device is aleady dedicate to the compute node,
do not execute the dedicate command.
By this way, we can implement:
1. Disconnect a FCP device when the FCP device is already dedicate to
the compute node.
2. Break the loop if the FCP device can't be found.
> [master] Don't dedicate fcp device if it already dedicate

- zvmsdk/vmactions/templates/grow_root_volume.j2
Two changes in this patch:
1. In some cases, the resize2fs cann't recognize the new extended partition space.
This patch add some sleep and retry to this operation.
2. In some scenario, the df output the wrong multipath name, so reload multipath mappings before we use df to find the root multipath name.
> add retry to the volume extend tool

- zvmsdk/vmactions/templates/grow_root_volume.j2
In some cases, the resize2fs cann't recognize the new extended partition space.
This patch add some sleep and retry to this operation.
> [1.5.n] add retry to the volume extend tool

- zvmsdk/volumeop.py
when the vm provision with both root and data volumes, the get_volume_connector would
be called for both the root and data volume. We need to add the assigner id in fcp database
so that we would get the same FCP devices with these get_volume_connector call.
> [Master]add assigner to the new allocated FCP in database

- zvmsdk/volumeop.py
when the vm provision with both root and data volumes, the get_volume_connector would
be called for both the root and data volume. We need to add the assigner id in fcp database
so that we would get the same FCP devices with these get_volume_connector call.
> [1.5.n] add assigner to the new allocated FCP in database

- zvmsdk/database.py
- zvmsdk/volumeop.py
We should just set the assigner id and not change the connections
in get_available_fcp. The connections are maintained in attach and detach
steps.
> [Master] Do not touch the connections in fcp database in get_available_fcp

- zvmsdk/database.py
- zvmsdk/volumeop.py
We should just set the assigner id and not change the connections
in get_available_fcp. The connections are maintained in attach and detach
steps.
> [1.5.n] Do not touch the connections in get_available_fcp

- zthin-parts/zthin/bin/unpackdiskimage
occasionlly there will be IOCTL error when using fdasd to set the
partiton table, this error happened when rereading the partion table,
it looks like a timing issue problem. And it will not cause the image
copy failure. The VM still can be boot up.
> [master] Ignore the fdasd error when create the partition table

- zthin-parts/zthin/bin/unpackdiskimage
occasionlly there will be IOCTL error when using fdasd to set the
partiton table, this error happened when rereading the partion table,
it looks like a timing issue problem. And it will not cause the image
copy failure. The VM still can be boot up.
> [1.5.n] Ignore the fdasd error when create the partition table

- zthin-parts/zthin/bin/unpackdiskimage
The disks for the same image will have the same UUID, it will cause mount
failed when deploy multiple disk with the same image
> [master] Using disk name to mount instead of UUID

- zthin-parts/zthin/bin/unpackdiskimage
The disks for the same image will have the same UUID, it will cause mount
failed when deploy multiple disk with the same image
> [1.5.n] Using disk name to mount instead of UUID

- zvmsdk/database.py
- zvmsdk/volumeop.py
when there's no available fcp for each path, just log error
and return [].
otherwise list index out of range syntax error reported.
> [master] fix the syntax error when no fcp available

- zvmsdk/database.py
- zvmsdk/volumeop.py
when there's no available fcp for each path, just log error
and return [].
otherwise list index out of range syntax error reported.
> [1.5.n] fix the syntax error when no fcp available

- smtLayer/vmUtils.py
eploy failure will left DASD undetached sometimes
> [Master] always execute disconnect disk in installFS

- zvmsdk/database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
With attach, there would be multiple fcp to be dedicated. Previously if
one fcp dedicate failed, only the current fcp will be rollback.
This PR will also rollback the previously dedicated fcps.
> [Master] rollback all dedicated fcp when got exception in dedicating fcp

- zvmsdk/database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
With attach, there would be multiple fcp to be dedicated. Previously if
one fcp dedicate failed, only the current fcp will be rollback.
This PR will also rollback the previously dedicated fcps.
Co-authored-by: Huang Rui <bjhuangr@users.noreply.github.com>
> [1.5.n]rollback all dedicated fcp when got exception (#249)

- smtLayer/vmUtils.py
backport:
deploy failure will left DASD undetached sometimes
> [1.5.n]deploy failure will left DASD undetached sometimes

- zvmsdk/config.py
backport:
change default value of timeout for waiting stop actions.
> [1.5.n]change default value of timeout for waiting stop actions

- zvmsdk/vmactions/templates/grow_root_volume.j2
1. get device name of root fs by 'lsblk' rather than 'df', as sometimes 'df' give stale dev name
2. execute 'partprobe' before 'resize2fs', so that 'resize2fs' can recognize the extended partition
> [Master]Fix boot volume not extend

- zvmsdk/vmactions/templates/grow_root_volume.j2
1. get device name of root fs by 'lsblk' rather than 'df', as sometimes 'df' give stale dev name
2. execute 'partprobe' before 'resize2fs', so that 'resize2fs' can recognize the extended partition
3. remove unnecessary check of multipath bindings
> [1.5.n]Fix boot volume not extend

- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
In the function get_volume_connector, if the reserve flag is True,
reserve the FCP device. If the reserve flag is False and the FCP's
connections is 0 then unreserve it.
> Add reserve flag to get_volume_connector

- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
In the function get_volume_connector, if the reserve flag is True,
reserve the FCP device. If the reserve flag is False and the FCP's
connections is 0 then unreserve it.
> [1.5.n]Add reserve flag to get_volume_connector

- zthin-parts/zthin/bin/refresh_bootmap
when the base vm root volume contains ephemeral or swap mounts in
/etc/fstab, and then when use this volume to clone new vm, the new
vm would failed to start because of these dirty mount entries.
This PR removed these ephemeral or swap mount lines from /etc/fstab
when deploying the new vm.
> [Master] remove the dirty mounts left in fstab when doing refreshbootmap

- zthin-parts/zthin/bin/refresh_bootmap
when the base vm root volume contains ephemeral or swap mounts in
/etc/fstab, and then when use this volume to clone new vm, the new
vm would failed to start because of these dirty mount entries.
This PR removed these ephemeral or swap mount lines from /etc/fstab
when deploying the new vm.
> [1.5.n] remove the dirty mounts left in fstab when doing refreshbootmap

- zthin-parts/zthin/bin/unpackdiskimage
it is used to avoid the ignition setting again when restart VM
> [master] remove firstboot from zipl after it has been executed

- zthin-parts/zthin/bin/unpackdiskimage
it is used to avoid the ignition setting again when restart VM
Co-authored-by: Huang Rui <bjhuangr@users.noreply.github.com>
> [1.5.n]remove firstboot from zipl after it has been executed (#262)

- zthin-parts/zthin/bin/refresh_bootmap
Remove stale /etc/multipath/bindings and /etc/multipath/wwids
These files may contain the old info of the captured base vm,
which disrupts the volume bindings of the new vm deployed from above captured image, resulting
a. mpath name inconsistent between 'df' and 'multipath'
b. in some scenairo, boot-volume extend partition fail due to 'a'
By removing them, they can be recreated later with correct volume bindings
when multipathd start at vm boot time.
Signed-off-by: Da Long Wang shdlwang@cn.ibm.com
> [Master]Remove stale /etc/multipath/bindings and /etc/multipath/wwids

- zthin-parts/zthin/bin/refresh_bootmap
Remove stale /etc/multipath/bindings and /etc/multipath/wwids
These files may contain the old info of the captured base vm,
which disrupts the volume bindings of the new vm deployed from above captured image, resulting
a. mpath name inconsistent between 'df' and 'multipath'
b. in some scenairo, boot-volume extend partition fail due to 'a'
By removing them, they can be recreated later with correct volume bindings
when multipathd start at vm boot time.
> [1.5.n]Remove stale /etc/multipath/bindings and /etc/multipath/wwids

- zthin-parts/zthin/bin/creatediskimage
1. set default compression level 6 when creating images with dasd type.
2. modify the --help message.
> [master] set default compression level when creating images with dasd type

- zthin-parts/zthin/bin/creatediskimage
1. set default compression level 6 when creating images with dasd type.
2. modify the --help message.
> [1.5.n] set compression level when creating images with dasd type

- zvmsdk/database.py
Change the way to allocate FCP devices. Use random way instead of
always return the first one. Because VM will be allocated the same FCP devices
if the FCP devices don't work.
> Random choose FCP devices

- zvmsdk/database.py
Change the way to allocate FCP devices. Use random way instead of
always return the first one. Because VM will be allocated the same FCP devices
if the FCP devices don't work.
> [1.5.n]Random choose FCP devices

- zthin-parts/zthin/bin/refresh_bootmap
In the current implementation, the script will use the first FCP and the first WWPN as the devNode.
But in some cases, files haven't been generated when we dedicate two FCP devices by executing smcli command. So this pr will traverse all FCP devices and all WWPNs to find a proper path.
> [master] Traverse FCP devices and WWPN info to look for a proper path

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Currently, we only support the continuous fcp_list in zvmsdk.conf.
This pr will support continuous fcp_list in zvmsdk.conf. 
For example:
fcp_list=5c70-5c71,5c73-5c74;5d70-5d71,5d73-5d74
or
fcp_list=5c73-5c74;5d70-5d71,5d73-5d74
> [master] Support uncontinous fcp_list

- test-requirements.txt
Ran 640 tests in 33.166s
OK (skipped=3)
py27 run-test: commands[1] | python -m unittest discover -v -s /root/python-zvm-sdk/smtLayer/tests/unit
test_getDiskPoolSpace3390 (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace3390Unknown (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace3390UnknownWithFlag (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336 (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336Unknown (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336UnknownWithFlag (test_getHost.SMTGetHostTestCase) ... ok
test_getReservedMemSize (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_equal_size (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_gap_G (test_makeVM.SMTMakeVMTestCase) ... ok …
> [master]remove PyYaml in test-requirement

- data/setupDisk
Signed-off-by: haolp <haolp@cn.ibm.com>
https://github.ibm.com/zvc/planning/issues/2698
```
OK
__________________________________________________________________ summary __________________________________________________________________
[root@UT python-zvm-sdk]# tox -e pep8
pep8 create: /root/python-zvm-sdk/.tox/pep8
pep8 installdeps: flake8
pep8 develop-inst: /root/python-zvm-sdk
pep8 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,attrs==19.3.0,certifi= …
```
> [master]add command to permanently online the disk for ubuntu

- data/setupDisk
Signed-off-by: haolp <haolp@cn.ibm.com>
```
OK
__________________________________________________________________ summary __________________________________________________________________
[root@UT python-zvm-sdk]# tox -e pep8
pep8 develop-inst-noop: /root/python-zvm-sdk
pep8 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,attrs==19.3.0,certifi==2020.6.20,chardet==3.0.4,configparser==4.0.2,contextlib2==0.6.0.post1,enum34==1.1.10,flake8==3.8.3,functools32= …
```
> [master]seperate path for ubuntu16 and 20 when permanently online the disk

- tools/share/zvmguestconfigure
Remove vmcp modprobe in zvmguestconfigure
> [master] Remove vmcp modprobe in zvmguestconfigure

- zvmsdk/sdkwsgi/requestlog.py
this is because the data type of X-Auth-Token in headers is bytes
but start_response expect unicode type.
so change the type hardly, still need finding the root cause.
> type error reported when sending requests to WSGI in zcc

- zthin-parts/zthin/bin/unpackdiskimage
This reverts commit 11f08c92967b4425724991e03d4a297695ada65a.
original PR here:
https://github.com/openmainframeproject/python-zvm-sdk/pull/293
> Revert "parted the partition from 64th track rather than 2nd track 

- smtLayer/vmUtils.py
Fixed two type error:
1. maxQuries value passed into the waitForVMState funtion is a float.
2. exception.output is a byte in python 3.
> fix the delete vm error

- setup.py
Fix the issue of volumeops/templates missing from python-zvm-sdk package.
Add these files as package data.
> [master] Add attach/detach template into zvmsdk

- zvmsdk/api.py
The default valume of dedicate_vdevs in guest_deploy API is "[]",
this will lead to unexpected value change assignment when python
interpret the module. So change the default value as "None".
> change guest_deploy parameter dedicate_vdevs default volume

- zvmsdk/smtclient.py
It is waste of time to mkfs against root disk, since the file
system format will be overwritten by the following disk dump.
So set the filesystem to 'none' to skip the mkfs.
> Do not perform mkfs against root disk

- zthin-parts/zthin/bin/refresh_bootmap
In the boot from volume scenario for RHEL, the VM may fail if the length of kernel parameter line exceeds the maximum allowed. So the production recommend is 8 different paths of rd.zfcp.
If the count of FCP devices is greater than 8, it will report an error and exit directly.
If the count of WWPN is greater than 8, it will report a warning and don't exit.
> Limit the length of rd.zfcp when refresh bootmap

- zthin-parts/zthin/bin/unpackdiskimage
The error code of rereading partition table for fdasd command has been changes
it will be 255 in package s390utils-base-2.4.0-1.el7.s390x for rhel7
and 1 in package s390utils-base-2.6.0-28.el8.s390x for rhel8
will ignore the error based on os version
> [master] Ignore the fdasd error for rereading partition table

- zthin-parts/zthin/bin/refresh_bootmap
If there are too many FCP devices, return the error message.
> Prompt error message if too many FCP paths

- zvmsdk/volumeop.py
Ignore the NotExistException when detaching a FCP device.
Because in some unexcepted cases, the connections of a FCP
device might be 0, at those cases, the volume can't detach
anymore. So we should handle this exception and set its
connections to 0.
> [master] Ignore not exist error when detaching device

- zvmsdk/vmops.py
The get console output failed due to python upgrade,
need to decode bytes in zvmsdk
> Get console output error due to python upgrade

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
596/6831 is really annoying error in DIRMAINT
we need handle it at upper layer to avoid report `false alarm`
> ignore 596/6831 in delete action

- doc/source/zvmsdk.conf.sample
- test-requirements.txt
- zvmsdk/config.py
- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/volumeop.py
https://github.ibm.com/zvc/planning/issues/3343
1.add another fcp pair selection algorithm
2.add a switch in zvmsdk.conf to switch between below two algo
* get_fcp_pair_with_same_index << added by this PR
* get_fcp_pair
> [master] get_fcp_pair_with_same_index

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
when detach/attach multiple volumes for a vm at same time, zvmguestconfiugre
will be restart too often to work well, and when detaching volume with previous
code, first to update database, then to punch scripts to vm and restart zvmguestcongure,
that may cause dirty data in the cases of concurrent detachment/attchment.
So I update code to make the zvmguestconfigure will be restarted only after the
last punch and reorder the sequence to first punch all scripts and then to update
database
> [master]zvmguestconfiugre supports multi-attach/detach at same time

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
Fix the problem that userid has beed deleted successfully but it
remain included in smapi namelist.
The root cause is exception raised when cleanup database records
and revoke access. In this change, will remove the userid from
smapi namelist immediately after it successfully deleted.
> cleanup namelist after userid deleted

- zvmsdk/dist.py
1. for v7k volume, if the lun id less than 256 will be decimal, otherwise will be hex;
2. For ds8k, the lun id will always be hex
@dongyanyang @jackydalong
> [master]update the lun id format to be  applicable for both v7k and ds8k

- zthin-parts/zthin/include/IUCV/iucvclient.h
- zthin-parts/zthin/src/IUCV/iucvclient.c
- zvmsdk/constants.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
If /etc/zvmsdk/iucv_authorized_userid file exists, will re-use the
userid when deploying new z/VM guests, and also re-use the userid
in iucv client.
> re-use previous IUCV authorized userid

- zvmsdk/dist.py
When capturing a sles vm with dns configured, and re-deploy the captured image,
the vm can not configure the new dns address correctly, so fix it.
> [master]fix dns configure error when deploying the captured sles image.

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/api.py
- zvmsdk/networkops.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
- zvmsdk/tests/unit/test_networkops.py
- zvmsdk/tests/unit/test_smtclient.py
add VLAN ID first into couple action
then replace old couple NIC to VSWITCH method from SMAPI call to Image_Replace_DM
Also, more important, couple NIC to VSWITCH as well by adding VLAN ID
> Add vlan id as param to couple_nic_to_vswitch function

- zvmsdk/api.py
- zvmsdk/config.py
- zvmsdk/hostops.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_hostops.py
- zvmsdk/tests/unit/test_smtclient.py
Please help review the code logic first, the ut and fvt will complete later on.
There's one point not quiet sure:
In guest_create() of api.py, if disk_list has only one disk info and disk_pool is None:
such as disk_list=[{'size':'1g', 'format':'xfs'}]  and disk_pool not configured in zvmsdk.conf
in such case, the guest_create report ERROR？or Continue( does boot_from_volume deploy vm go into this guest_create() fucntion in api.py?)
To support CIC manage a zvm host without diskpool, such as
zvm host configured FCP stroage only, we do the corresponding
change to support disk_pool to None by default.
Code changes:
- Add extra check for disk_pool=None before previous check logic
> guest_create
> host_diskpool_get_info
> get_info
> add_mdisks
> _add_mdisk
- Not call Image_Volume_Space_Query_DM …
> [Master]Support disk_pool to None by default

- zvmsdk/dist.py
- zvmsdk/volumeops/templates/rhel8_attach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
1. add more comments to explain the function of commands
2. rhel7_detach_volume.j2 template compared to old version:
- fix bug of multipath command output has leftover and bug of attaching time is too long, they are because `user_friendly_names` set to yes, and the parameter of `multipath -f` should be map name instead of wwid. and if the `user_friendly_names` set to no, it still can work.
- add unit_remove if auto-lun-scan is disabled in detachment script template.
3. rhel7_detach_volume.j2 compared to old version:
- add port_rescan if auto-scan is disabled in attachment script template.
> [master]update punch scripts of attachment and detachment

- setup.py
fix for PR: https://github.com/openmainframeproject/feilong/pull/372
forget to add rhel8_attach_volume.j2 and rhel8_detach_volume.j2 into package data.
> [master]forget adding templates into package data

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
In live_resize_memory implementation, _get_active_memory is
called to parse 'lsmem' output to get current active memory.
'lsmem' output format is changed, this commit
is update _get_active_memory to support new lsmem output format.
Have tested with RHEL7.8, RHEL7.9, RHEL8.2, RHEL8.3 and
SLES15SP2, Ubuntu20.
> [master]Improve live_resize_memory API to support new lsmem ouput format

- zvmsdk/returncode.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
For Ubuntu, "chcpu -r" command can't make
new defined cpus online, need do an extra
"chcpu -e <cpu-list>" command.
> [master] Update smtclient live_resize_cpus

- zvmsdk/volumeops/templates/rhel7_detach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
we execute multipath -f will meet 2 error cases:
1. `multipath -f <with a none input>`, it will report error 'must provide a map name'
2. `multipath -f map_name_in_use`, it will report error 'in use'
but the exit code $? of the 2 errors are same, it is 1.
so need to diff them.
> [master] fix exit code bug in detach scripts

- zthin-parts/zthin/src/smcliImage.c
Image_SCSI_Characteristics_Define_DM expects all options
to be there and this assumption is wrong, we should allow
most of them (except the name of the user ) to be optional
> fix Image_SCSI_Characteristics_Define_DM usage

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
The /dev/disk/by-path/ does not have FCP folder, shouldn't do that check.
The FCP is not offline because error in zthin lib, which leads to leftovers
on compute node after refreshbootmap.
> fix error of FCP not offline and add some log prints

- doc/source/errcode.csv
- doc/source/zvmsdk.conf.sample
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/config.py
- zvmsdk/exception.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/vmops.py
By adding a timeout parameter to guest_start api. Default timeout
is 0, which means not wait for guest reachable status. If timeout
> 0, will wait guest to reachable status or timeout to return.
> add reachable check in guest_start

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
the bug is that:
sometimes get_available_fcp will return the fcp_list whose
len is less the count of multipath
> [master]fix fcp database allocation bug

- doc/source/zvmsdk.conf.sample
- zvmsdk/config.py
Related issue: https://github.ibm.com/zvc/planning/issues/4962
We shouldn't set default_admin_userid in the beginning of a line.
> [master] Fix duplicated default_admin_userid in zvmsdk.conf

- zthin-parts/zthin/bin/unpackdiskimage
For failing to get boot and root partitions of RHCOS4.7 correctly by using hexdump,
we change to all use fdisk to get partitions.
> Use fdisk to get boot and root partitions for RHCOS in unpackdiskimage

- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
there is a bug in PR: https://github.com/openmainframeproject/feilong/pull/393
I forgot the case that get_available_fcp will also be called when detaching volumes.
So because my changes, when detach, get_available_fcp will allocated new FCPs for the already detached volumes:
this will lead to problem:
the FCPs used to detach are different from the FCPs cinder used to cleanup.
this will make the FCPs chaos and left some hosts unmap on storage.
> [master]fix bug in get_available_fcp

- zthin-parts/zthin/bin/refresh_bootmap
- zvmsdk/api.py
- zvmsdk/smtclient.py
Previously we return the FCPs and WWPNs in a seperate list in the refreshbootmap API
which assumes all the FCP devices have access to all the WWPNs.
This does not stand for all customer scenarios.
This change will find all valid paths while attaching the volume.
and return the valid paths in a dict of format:
{'FCP1': ['W1','W2'], "FCP2": ['W3', 'W4']}
> [master] update refreshbootmap API to return a dict

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
596/3543 is actually a supported behavior, which is , delete a VM with  VDISK might lead to this warning
if cleanup is set to true, so ignore the warning
> ignore 596/3543 warnning

- zthin-parts/zthin/bin/refresh_bootmap
From RHCOS4.7, the boot partition became the third partition,
not the first partition. This will cause the error when checking
devnode in refreshzipl of refresh_bootmap script.
In this change, return from refreshzipl directly if skipzipl.
> update refresh_bootmap for RHCOS4.7

- zthin-parts/zthin/bin/unpackdiskimage
With mpath enabled, the dev node should be "/dev/mapper/mpathXN",
where "X" is dev and "N" is partition. For example,
"/dev/mapper/mpatha3". In this change, will check mpath enabled or
not, then set the dev node string accordingly.
> To fix the error when mount RHCOS partition with mpath enabled

- smtLayer/vmUtils.py
> Fix a typo fdsik ==> fdisk to avoid confusion

- doc/source/errcode.csv
- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/returncode.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
If maximum memory is set to a large value such as 256G and
deploy a vm with 4G memory, the reserved memory is 252G,
then zvm guest linux can't start smoothly. Make the reserved
memory value as 248G can work.
To make sure VM can start correctly,
when maximum memory - active memory <= 248G:
reserved memory = maximum memory - active memory
when maximum memory - active memory > 248G:
reserved memory = 248G
> [master]Make maximum reserved memory as 248G

- zthin-parts/zthin/bin/refresh_bootmap
```shell
Add retry below
sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22 34 60 90 120"
```
```shell
1. At the start of refresh_bootmap, mv devNode file to /tmp/refresh/ manually 
---------
[root@113-cmp-wdl-m5403 ~]# while true; do ls -lh /dev/disk/by-id/dm-uuid*; /bin/mv /dev/disk/by-id/dm-uuid-part1-mpath-* /tmp/refresh/; ls -lh /tmp/refresh/; sleep 0.5; done;
----------
-> trigger retry
2. Before retry attempts exhausted, mv devNode file back to /dev/disk/by-id/ 
-> refresh_bootmap completed 
key related log of /var/log/messages:
refreshZIPL: Begin to refreshZIPL.
refreshZIPL: devNode file /dev/disk/by-id/dm-uuid-part1-mpath-3600507640083826de000000000002192 not exist yet. Retrying...
refreshZIPL: Retrying with interval as .001 seconds
refreshZIPL: Retrying with interval as .01 seconds …
```
> [master] add retry for find devNode file when refresh_bootmap

- smtLayer/vmUtils.py
The add 9336 function does not contain enough information about fdisk actions result
> Add output into log for debug purpose

- zvmsdk/volumeops/templates/rhel7_detach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
No matter the data volume attached is in use or not, will clean up the leftover of data volume to be detached.
> [master]Ignore the exit code of multipath -f command to continue clean up the leftover of data volume.

- zthin-parts/zthin/bin/refresh_bootmap
Before the change, we use 'multipath -F -W' to flush all multipath map,
this may cause error in concurrent BFV deploys or affeect multipath devices
owned by the zcc node.
This change:
1. change to use 'multipath -f' and 'multipath -w' to flush only the BFV root volume
(if use `multipath -f -w` in a single cmd, the wwid won't be removed from the wwids file. So separate this
into two cmds.)
2. in order to implement 1, we move the multipath flush steps ahead of disconnectFCP. Otherwise
we will fail to find the mpath_name.
> [master]update refreshbootmap to only flush the BFV root volume

- zthin-parts/zthin/bin/unpackdiskimage
The change is for RHCOS boot from volume. In cleanup, sometimes
can not get mpath map name. Add a "multipath" before the
"multipath -f" to make sure the mapth discovered.
> detect mpath befor flush the mpath

- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
Currently when creating a VM, when defined memory size equals
max memory size, then reserved memory size is cacluted as 0,
then even setReservedMem is specified, there is not a line"
"COMMAND DEF STOR RESERVED xxx" written into user direct entry.
It causes a problem that when users try to do cold resize to
decrease VM's memory size, then the new defined memory size
< max memory size, reserved memory size > 0. Then a new line
"COMMAND DEF STOR RESERVED xxx" need be added into user direct
entry. Besides, current memory resize implementation would try
to fetch the original reserved memory value from user direct,
if none obtained, resizing reports error.
So to support cold resize working correctly and make things easier,
we write COMMAND DEF STOR RESERVED 0M" in user direct when its
defined …
> [master]Write "COMMAND DEF STOR RESERVED 0M" in user direct when creating vm

- doc/source/errcode.csv
- doc/source/zvmsdk.conf.sample
- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/config.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_config.py
- zvmsdk/tests/unit/test_smtclient.py
When reserved memory is too large, VM can't boot.
So we introduce a user_default_max_reserved_memory
config item in zvmsdk.conf. It's default value
is 128G, users can also set it by themselves.
Then when vm is created or resized, the reserved
storage value in user direct entry can't be greater
than user_default_max_reserved_memory value.
Default user_default_max_memory value is also
set to 128G.
> [master]Add new config item: user_default_max_reserved_memory

- zthin-parts/zthin/bin/unpackdiskimage
Remove zfcp.allow_lun_scan=0 from kernel cmdline, to detect mpath
automatically after virtual machine deploy.
Without this change, user should setup multipath manually.
> allow zfcp lun scan for RHCOS boot from volume

- doc/source/zvmsdk.conf.sample
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/config.py
- zvmsdk/tests/unit/test_api.py
This commit is to make user_default_max_memory
and user_default_max_reserved_memory default value
as 64G.
> [master]Make user_default_max_memory default value as 64G

- zthin-parts/zthin/bin/refresh_bootmap
The fix includes two parts.
part 1: cleanup leftover after phase1 of BFV(i.e. dd qcow2 image to volume)
part 2: cleanup leftover after phase2 of BFV(i.e. refresh_bootmap)
This PR is only for part 2.
> [master] cleanup multipath leftover caused in BFV

- zthin-parts/zthin/bin/refresh_bootmap
we have find that the mount of /run folder in a chroot case would
cause the system down, (the /run folder files in the system is lost.)
and I checked several pages related to chroot without the mount of /run folder
and some page explicitly mentioned /run is not recommended to be mounted.
so remove the mount of /run from our code.
> don't mount the /run folder for chroot zipl

- smtLayer/vmUtils.py
previously, we use `d` in fdisk which is delete a parition
```  Generic
d   delete a partition
```
but this might fail due to multiple partitions existing
so the PR process to recreate the parittion table by using `g` which is 
```
Create a new label
g   create a new empty GPT partition table
```
> use g instead of d when fdisk

- .github/workflows/pr.yaml
Remove the python version 2.7 check test as the CI python 2.7 env cannot run py36 test.
The python version 3.6 check test in github action still can run both py27 and py36 test.
https://github.com/openmainframeproject/feilong/runs/2031436212?check_suite_focus=true
The HTML pages are in doc/build/html.
___________________________________ summary ____________________________________
pep8: commands succeeded
> Fix the ci failure

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
1. use `lszfcp -P` to replace the `lsluns` to find the valid target ports
2. for the valid (fcp, wwpn) combination, do the unit_add/unit_remove to fit the disable of allow_lun_scan
3. fix the issue of wwpns variable be overwritten
4. add util functions in zthinutil to each sub task, eg addlun, removelun, dedicateonlineFCP, offlineUndedicateFCP
5. fix the issue of multiple times offline operation to each FCP device. (previous logs contain many entried like "FCP xxx is already offline")
> refine refreshbootmap code

- zthin-parts/zthin/bin/unpackdiskimage
Indicate all valid wwpns by trying unit_add, add all valid paths
as rd.zfcp parameter in rhcos kernel cmdline.
unit_remove will be handled in following PR.
> add multiple paths for single fcp into rhcos kernel cmdline

- zthin-parts/zthin/bin/refresh_bootmap
In the current refreshbootmap implementation, we use chroot to do zipl to refresh the bootloader of guest vm. In order to be able to chroot, we need to bind mount several system dirs of the compute node
This implementation has been proofed to sometimes cause the compute system down：
It is dangerous to mount system dirs and chroot. And zipl command has the support of specifying the initramfs/kernel path parameter to refresh bootloader.
With this PR:
- it changes temporary mount point from /mnt to /tmp
- it enable zipl for RHEL7/RHEL8 without chroot by specifing the path of zipl.conf and BootLoaderSpec dir.
```shell
#RHEL8 support use -b to specify BootLoaderSpec files
${deviceMountPoint}/usr/sbin/zipl -V \
-c ${deviceMountPoint}/etc/zipl.conf \
-b ${deviceMountPoint}/boot/loader/entries …
```
> [master] zipl without chroot

- zthin-parts/zthin/bin/refresh_bootmap
if zfcp module is manually removed by user, when we add it back, we should disable it.
> disable allow_lun_scan when modprobe zfcp

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/getHost.py
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/constants.py
- zvmsdk/hostops.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/host.py
- zvmsdk/smtclient.py
- zvmsdk/tests/fvt/api_templates/test_host_disk_volumes.tpl
- zvmsdk/tests/unit/sdkwsgi/handlers/test_host.py
- zvmsdk/tests/unit/sdkwsgi/test_handler.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_hostops.py
- zvmsdk/tests/unit/test_smtclient.py
for which we can match the volumes with the one in the vm user direct.
So add these interfaces to get the disk volumes of the diskpool.
If the diskpool is provided, query the voluems of the pool, if not,
the CONF.zvm.disk_pool will be used.
> [master]Add interfaces to get disk volumes of the diskpool

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/fvt/api_templates/test_get_all_fcp_usage.tpl
- zvmsdk/tests/fvt/api_templates/test_get_fcp_usage.tpl
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
this API is used to set connections and reserved values
in database when initialize_connection or terminate_connection fail.
> add APIs of operating FCP usage

- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/restapi.rst
- zthin-parts/zthin/bin/refresh_bootmap
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/dist.py
- zvmsdk/networkops.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/fvt/api_templates/test_refresh_bootmap.tpl
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_dist.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/volumeop.py
Move the steps in RHCOS BFV from unpackdiskimage to refresh_bootmap:
- inject ignition file onto RHCOS boot partition
- get nicID and ipConfig to construct rd.znet and ip kernel cmdline
and write into BLS file
- refresh bootmap for RHCOS root volume
Add new parameters to the API volume_refresh_bootmap:
- transportfiles: as ignition file
- guest_networks: for getting network info for kernel cmdline
Add logic to inject ignition file into RHCOS boot partition,
generate kernel cmdline and run zipl to setup bootmap.
Support both RHCOS4.6 and RHCOS4.7
> refresh bootmap for RHCOS

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
code change:
1. Add VM start operation after capture active VM completed successful.
2. change unit test cases.
> [master]Add restart action after catpure active VM completed successfully.

- zvmsdk/api.py
- zvmsdk/tests/unit/test_api.py
In guest_register, currently MAC address info is fetched
from NICDEF statements in VM's user direct entry. But it
is possible that NICDEF statements don't contain MAC
address information, which results in port information
not written to switch table in zvmsdk network database.
This commit changes the way of getting MAC address info
by using get_adapters_info, which ensures the MAC address
could always be fetched.
> [master]Update a way to get MAC address info in guest_register

- zvmsdk/vmactions/templates/grow_root_volume.j2
Add extend support for the following disklayout:
part1: non-lvm /
part2: lvm physical volume
Extend the physical volume for this scenario. (vg will automatically discover the resized pv.)
> extend the second partition of lvm disk layout

- zthin-parts/zthin/bin/refresh_bootmap
when lvmetad is enabled, the vm with lvm disklayout would sometimes
enter emergenecy mode during reboot.
This commit set the use_lvmetad as 0 at the refreshbootmap stage.
> disable lvmetad to avoid bfv vm enter emergency mode

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
with the feature introduced here, we are able to provision VM by adding a comment like
`* ABCD this is a comment ` into user direct
> Add support of comment of user direct

- doc/source/errcode.csv
- doc/source/restapi.rst
- zvmsdk/api.py
- zvmsdk/exception.py
- zvmsdk/returncode.py
- zvmsdk/tests/unit/test_api.py
Currently guest_get_power_state returns shutdown if the guest userid
exists in DB but does not exist in user directory (e.g. it has been
deleted through smcli directly), and this is wrong which could cause
confusion and unexpected result.
Also because if the userid does not exist in DB, it returns 404.
Hence, the fix returns 404 to caller in this case.
> [master] Add check if user directory exists in guest_get_power_state

- zvmsdk/database.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_smtclient.py
code change:  try get os version from guest db  when try capture shutoff status instance.
Signed-off-by: wngzhe <wngzhe@cn.ibm.com>
> [master] Try get os version when capture shutoff vm

- tools/share/zvmguestconfigure
with PR: https://github.com/openmainframeproject/feilong/pull/336/files
the loop device will only be setup when the cfgdrive is first recieved.
But the loop device will be lost at system reboot which will cause cloud-init
to think the first reboot is the first boot.
This PR will check whether the device with config-2 label (which cloud-init use as configdrive souce)
already exists, create the loop device only if it does not exist.
> fix the loop device lost when reboot

- zthin-parts/zthin/bin/refresh_bootmap
1. some times the multipath is left there even though the multipath flush cmd reports successful
If we delete the wwids and bindings, the same name maybe reused by future deploy.
2. enhance the logs to collect more info.
> don't remove the wwids and bindings at the end of refreshbootmap

- zthin-parts/zthin/bin/refresh_bootmap
there are some case that the umount may fail, we should continue to do
the cleanup, otherwise the fcps/lun will be left on the compute node.
> continue to do the cleanup of multipath/FCP/lun when umount fails

- zthin-parts/zthin/bin/refresh_bootmap
In some case, though the `multipath -f` reported the multipath device is flushed successfully, multipathd will continue to add new path into the mpath device making the mpath device showing up again and the LVs on it then automatically be activated.
This flow would cause LVs and multipath device left on the compute node.
So we add the check of mpath existence again at the end and do the deactivate of LVs and flush mpath device, to try our best to avoid leftover issue.
> try to deactivate lv and flush mpath again before exit the refreshbootmap

- zvmsdk/api.py
- zvmsdk/tests/unit/test_api.py
If disk_pool is not configured, host_get_diskpool_volumes api
will return {}, not report error.
> [master]Support disk_pool is None for host_get_diskpool_volumes api

- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
CPU schedule statement is supported so that when a parm is given such as schedule pool1 then
we have following statement in user direct
COMMAND SCHEDULE * WITHIN POOL POOL1
> add cpu schedule statement support

- zthin-parts/zthin/bin/unpackdiskimage
Originally the log file of unpackdiskimage is like unpackdiskimage_trace_2021-07-23-08:30:36.812.txt
which can not be parsed by the support system. Change ':' to '_' can solve it.
> Replace the ':' in the log file name to be '_'

- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
Add support for COMMAND SET VMRELOCATE * DOMAIN Z15ONLY
so that we can set those domain values in the code to provide granularity
> Add support for COMMAND SET VMRELOCATE * DOMAIN Z15ONLY

- zthin-parts/zthin/src/smcliVMRelocate.c
Originally info is not enough for the user to understand the usage,
the new added info and check is helpful for it.
> [master] Provide more helpful information and checks in 'smcli VMRELOCATE'

- zthin-parts/zthin/bin/unpackdiskimage
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
Fix for https://github.com/openmainframeproject/feilong/pull/511/files#r707124523
Local test passed:
[2021-09-13 05:11:49] [INFO] Image header info in guest_deploy: rc: 0, header:
00000000  78 43 41 54 20 43 4b 44  20 44 69 73 6b 20 49 6d  |xCAT CKD Disk Im|
00000010  61 67 65 3a 20 20 20 20  20 20 20 31 34 35 36 34  |age:       14564|
00000020  20 43 59 4c 20 48 4c 65  6e 3a 20 30 30 35 35 20  | CYL HLen: 0055 |
00000030  47 5a 49 50 3a 20 36 20  20 20 20 20 20 20 20 20  |GZIP: 6         |
00000040
> [master] fix debug dasd

- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
only update database when destroy instance and no need rollback in some cases
related issue: https://github.ibm.com/zvc/planning/issues/7111#issuecomment-35536539
Signed-off-by: flytiger <flytiger@flytiger-PC.cn.ibm.com>
> only update database when destroy instance

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
when call decreas_usage/increase_usage with a not existing FCP will raise exception 'out of index'.
Signed-off-by: flytiger <flytiger@flytiger-PC.cn.ibm.com>
> fix bugs in decrease/increase fcp usage of database

- smtLayer/migrateVM.py
- zvmsdk/api.py
- zvmsdk/smtclient.py
The destination ID in the virtual machine's /etc/iucv_authorized_userid
should be set to the target compute node's after the migration succeeds.
Otherwise, it will cause trouble if migration fails.
There are errors in the arguments' handling of maxtotal, maxquiesce,
force and immediate.
The fix makes them work.
> [master] fix live migrate

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
```
2119T Error in CMS command; RC= rc
from: command parameter_string
at line line.
Explanation:
The CP or CMS command shown resulted in a non-zero
return code. This message is frequently preceded by
a DMK, HCP, or DMS error message that describes
the cause. The most common causes of this problem
(in order) are: (a) one of the service machine's disks
has gotten full, usually the PTH (primary transaction
history) disk or the STH (secondary transaction history
disk) listed in the DVHPROFA file with the service
machine's user ID as the filetype; or (b) the service
machine's virtual storage size is insufficient to process
a particularly large data file; or (c) a long
```
see this error in our test env
> Fix 596/2119 issue

- .gitignore
- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
1. previously we would get the valid combination of (fcp,wwpn) after checking the disk path existence.
if some path does not show up in compute node, we would take it as invalid. Then if all paths on some fcp
do not show up, no paths from this fcp will be defined in rd.zfcp and also not in vm user definition.
This change skip the check of whether the disk path show up, take all paths in `lszfcp -P` as valid paths to
define the rd.zfcp and vm definition.
2. increase the sleep time to wait longer for the disk showup.
Previously we run into case that the disk would finally showup but we didn't wait that long.
> fix the issue that some FCP may not be defined in BFV vm definition

- zthin-parts/zthin/bin/refresh_bootmap
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/volumeop.py
Before this change, the wwid is get from the scsi_id cmd on a single path after we find
a valid disk show up on the compute node.
But in some error case that the refreshbootmap may fail in very early stage before we find a valid path, eg
when failed to online some FCPs, or no valid path found on any FCPs, in these cases, the wwid maybe "". Then
when doing cleanup at the exit of refreshbootmap, we cann't get the multipath map name (eg, mpatha) from wwid and
then we cann't do the cleanup of the mpath and disk.
so this change would accept wwid as a parameter and use it directly in the cleanup.
> add wwid as a parameter for refresh_bootmap

- zthin-parts/zthin/bin/refresh_bootmap
variable paths_count is renamed to valid_paths_count in previous commit.
> fix a regression issue to rhcos BFV in previous refreshbootmap change

- zthin-parts/zthin/bin/refresh_bootmap
By default, the UUID is used as the root path when starting the OS.
Previously we only hardcode to mpath path as root for "RHEL8".
For RHEL7, we still use the default root fs UUID. But in our test, we
found that RHEL7 may also use single path as root when system boot.
This commit change the RHEL7 to explicitly specify mpath path as root.
> update rhel7 kernel cmdline to use mpath as the root

- zthin-parts/zthin/lib/zthinshellutils
- zvmsdk/config.py
- zvmsdk/tests/unit/test_smtclient.py
1. udevadm settle is not required to add a SCSI disk to Linux, the unit_add will wait for that to
be ready.
2. the refrehsbootmap timeout would cause potential side-effects, so enlarge the default timeout value
from 600s to 1200s.
> remove udevsettle from addLun and increase the refreshbootmap timeout from 600s to 1200s

- zthin-parts/zthin/bin/refresh_bootmap
previously we will check the mpath existence again after the lun removed
and fcp devices offline, because we have found there's chance that the multipathd
readded the map again after it is flushed.
But the check will based on whether the /dev/mapper/$map_name file exists. Recently
we find that there's scenario the /dev/mapper/$map_name does not exist while it exists
in the output of 'multipath -l'.
So in this fix, we removed the check of '/dev/mapper/$map_name'， just do the leftover
check and flush again at the end, no side-effect of doing this.
> enhance to leftover handling

- zvmsdk/database.py
- zvmsdk/hostops.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/volumeop.py
the output of get_all_fcp_usage is reserved, connections, for exmaple:
```
[2021-11-22 00:53:21] [INFO] Got all fcp usage: [('1d0e', 'YDYD00C9', 0, 0, 1), ('1d0d', 'YDYD00C8', 1, 2, 1),
```
the output of got get_available_fcp is connections,reserved, for example:
```
[2021-11-22 00:53:37] [INFO] Got fcp records [('1b0e', 'YDYD00C8', 2, 1, 0, ''), ('1d0d', 'YDYD00C8', 2, 1, 1, '')]
```
> the sequence of reserved and connections in log was not consistent

- doc/source/errcode.csv
- doc/source/zvmsdk.conf.sample
- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/lib/zthinshellutils
- zvmsdk/config.py
- zvmsdk/database.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/volumeop.py
1. add the option min_fcp_path_count. If available FCP >= min_fcp_path_count, do not report error
and make the BFV can continue, including the two stage would have this check:
a. allocating FCP (some path may not have free FCPs any more, but other paths have)
b. refreshbootmap stage (some FCPs may failed to be dedicated or online)
2. To make the FCP database consistent with the FCPs defined to vm, compare the valid_path_string
returned by refreshbootmap, if some fcps allocated but found not usable to be defined in vm, then
mark the fcp unreserved in database.
3. Make the refreshbootmap error msg clean. Previously all msgs printed with prefix "ERROR:" would be printed
in API response and UI msg, which may look like below:
```
Refresh bootmap fails, error code: 10 and reason: \\nERROR: An …
```
> add min_fcp_path_count to handle some FCP not available

- zvmsdk/volumeop.py
In previous PR: https://github.com/openmainframeproject/feilong/pull/538
we have this:
> To make the FCP database consistent with the FCPs defined to vm, compare the valid_path_string
>returned by refreshbootmap, if some fcps allocated but found not usable to be defined in vm, then
>mark the fcp unreserved in database.
But this would cause the FCP marked as reserved=0 and connections=1, and also since these FCPs are
already defined in the storage host, we cann't mark them as free.
So this patch would remove the check and keep the unusable FCPs marked as in-use.
> Remove the FCP database rollback logic commited in PR: https://github.com/openmainframeproject/feilong/pull/538

- zthin-parts/zthin/bin/refresh_bootmap
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
so that in the upper layer we can check whether the allocated FCP
count equals to the configured total path count. If not equal,
we then can log and send warning msg to end user.
> return the total fcp paths count in get_volume_connector

- zvmsdk/api.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
This can speed up the match of host when finding the host on the storage
backend with supplied wwpns.
> return the lparname_userid as the host value in get_volume_connector

- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
- Before this PR, FCP DB will not by updated when restarting sdkserver
- With this PR, FCP DB will be synced in the following order
First, sync with the fcp_list of zvmsdk.conf
Second, sync with FCP status queried by smcli System_WWPN_Query to z/VM
> [master] sync FCP DB when restart sdkserver

- zvmsdk/api.py
- zvmsdk/sdkwsgi/schemas/guest.py
So that no need to set the userid for the onboarded guest
which has no permission. Without this, LGR can still work.
> [master] Support dest_zcc_userid to be None

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
if the instance template specified in config.properties is lower case
assign() operation may cause assigner_id in db become lower case
so transfer to upper case every time before calling assign
> avoid lower case assigner_id in database

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
implement_TODO_for_PR_541,
which enables ZCC API get_all_fcp_usage() to sync db with zvm before reading fcp info from db
> [master] implement_TODO_for_PR_541

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Fixed items:
- _sync_db_with_zvm() need to update 'Owner' in DB
- get_all_fcp_usage() will log if the assigner_id-in-DB differs from owner-returned-by-zvm
- get_all_fcp_usage() change format of unallocated_but_active
> [master] save and return FCP owner

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
In couple_nic_to_vswitch, Image Directory is replaced by adding
vswitch to NICDEF statement. If the user directory NICDEF
statment already included the specified switch, means the NIC has
already coupled to the vswitch, error happens when running above
actions.
This commit is to skip replace direct and nic couple when
vswitch exists in NICDEF. A user scenario is when a VM is migrating
to a target host. The target host detected the device add and call
into couple nic to vswitch.
> Skip replace direct and nic couple when vswitch exists in NICDEF

- zthin-parts/zthin/lib/zthinshellutils
Before the change, the default size 1KB is used as the maximum length
of each single msg. So when the msg length exceeds that length, the msg
will be truncated.
With this fix, the msg size is dynamically set according to the msg length.
> set the maximum log msg size depending on the msg length

- zthin-parts/zthin/bin/refresh_bootmap
> make error msg more clear when no valid path found between FCP and WWPN

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
With the PR,
- within get_available_fcp:
before call get_fcp_pairXXX to allocate FCPs for the initial attachment against a VM,
call sync_db_with_zvm to update FCP state in FCP DB based on the info queried from z/VM
```python
get_volume_connector
get_available_fcp
get_fcp_pair_with_same_index
or
get_fcp_pair
```
- within get_fcp_pairXXX, the available FCPs should meet the following conditions:
```
connections = 0
reserved = 0
state = free  <<<< new added condition in this PR
```
> [master] assign_FCPs_with_free_state_for_attachment

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/bin/unpackdiskimage
After the hard reboot of rhcos, network connection will be broken
once LGR to another SSI member.
The root cause is, in current implementation, rhcos network will
be configured via "ip=" kernel parameter, not leveraging
NetworkManager network connection config file.
Fix this by remove "rd.neednet=1", "ip=" and "nameserver=" kernel
parameters from rhcos BLS config file after run zipl.
> fix rhcos network connection issue after LGR

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
- Add _shrink_fcp_list() to transform a list to string, 
```python                                                 
def _shrink_fcp_list(self, fcp_list):
""" Transform a FCP list to a string.
:param fcp_list: (list) a list object contains FCPs.
Case 1: only one FCP in the list.
e.g. fcp_list = ['1A01']
Case 2: all the FCPs are continuous.
e.g. fcp_list =['1A01', '1A02', '1A03']
Case 3: not all the FCPs are continuous.
e.g. fcp_list = ['1A01', '1A02', '1A03',
'1A05',
'1AFF', '1B00', '1B01',
'1B04']
Case 4: an empty list.
e.g. fcp_list = []
:return fcp_str: (str)
Case 1: fcp_str = '1A01'
Case 2: fcp_str = '1A01 - 1A03'
Case 3: fcp_str = '1A01 - 1A03, 1A05,
1AFF - 1B01, 1B04'
Case 4: fcp_str = ''
"""                                                 
```
- Hence, enabling ZCC API …
> [master] transform_fcp_list_to_str

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
Fix the indexerror when attempt to allocate FCPs from an empty FCP DB
if use get_fcp_pair_with_same_index=1 of /etc/zvmsdk/zvmsdk.conf
> [master] fix_indexerr_when_fcp_db_empty

- zthin-parts/scripts/unpackdiskimage
In zcc, unpackdiskimage
has error printError "Target disk is too small for specified image.”
Add more information here, similar like other functions.
> Add more information in the log when disk is not large enough

- zvmsdk/database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Add the following 3 sections in the return value of ZCC API get_all_fcp_usage()
```
- reserved_only :   for FCPs with connections  = 0 and reserved = 1
- connections_only: for FCPs with connections != 0 and reserved = 0
- total:            for all the FCPs in the corresponding path
```
example of the return value  of ZCC API get_all_fcp_usage()
> [master] add_3_section_for_get_all_fcp_usage_api

- zvmsdk/hostops.py
- zvmsdk/tests/unit/test_hostops.py
Current guest_list function eventually calls
SMAPI Image_Name_Query_DM to get a list of defined
virtual images on the z/VM. If the z/VM is an
SSI cluster member, it could get
guests on other z/VMs in the same SSI cluster.
Need get rid of these guests from the guest_list
results.
> [master] Update guest_list function for z/VM in an SSI cluster

- zthin-parts/zthin/bin/refresh_bootmap
Fix the variable substitue error of refreshbootmap.
> fix the syntax error in refreshbootmap

- zthin-parts/zthin/bin/refresh_bootmap
Although we have the 2nd time flush of multipath leftovers at the
end of the cleanup (luns and FCPs are already deleted), but the flush
method "multipath -f" still won't work under some case.
This PR add a 3ird time flush, which would use "dmsetup suspend" and
"dmsetup remove -f" to forcely do flush again.
> add "dmsetup suspend and remove" to force flush leftover again

- zthin-parts/zthin/bin/unpackdiskimage
Signed-off-by: “haoxy” <haoxy@cn.ibm.com>
in zcc, unpackdiskimage has error,  printError "Target disk is too small for specified image."
There is already a PR https://github.com/openmainframeproject/feilong/pull/576 days ago which updated unpackdiskimage under scripts/.  BOE1 fba disk pool has not worked till Jan 13 tonight, so just find the problems: 
1.  There are two files named unpackdiskimage in feilong.  It seems it is the copy under bin takes effect.  So need to change again.
2. These 2 PRs are hard to be verified because the changed code are in **deployFBAImage** function.  In unpackdiskimage , there are deployFBAptImage and deployFBAImage functions handling fba image.  I have tested all 5 existed fba images (rhel82_ext4_fba.img, rhel78_ext4_fba.img, sles15fba_new.img, …
> Add more info for unpackdiskimage under zthin-parts/zthin/bin/

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
Current implementation in smtclient.py, if USER Directory Statement has
fields number not equal to 6, then defined memory and reserved memory value
of the userid are fetched as -1, which leads to memory resize failure.
With this commit, it is not strictly requires the USER Directory Statement
have 6 fields, because there are real cases that has 7 fields.
Now it is to check the fields number is not fewer than 6.
> [master]Support resize memory when USER Directory Statement has more than 6 fields

- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/volumeop.py
According the new design, user can specify a fcp template while choosing fcp devices, so need to update thee related APIs.
In this PR, updated the api `get_volume_connector`.
Here are some examples to run the api:
1. with `fcp_template_id` specified while attaching volume:
```
>>> conn.send_request('get_volume_connector', 'WXY00007', reserve=True, fcp_template_id='0002')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zvm_fcp': ['1c13', '1d1e'], 'wwpns': ['c05076de33000355', 'c05076de330003c2'], 'phy_to_virt_initiators': {'c05076de33000355': 'c05076de33002641', 'c05076de330003c2': 'c05076de33002e41'}, 'host': 'BOEM5401_WXY00007', 'fcp_paths': 2, 'fcp_template_id': '0002'}}
```
2. without `fcp_template_id` specified, …
> Update API get_volume_connection with fcp template

- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/volumeop.py
1. rename the following var names on ZCC
```
default_of_sps  -> default_sp_list
default_of_host -> host_default
```
2. change
```
if (wwpn_npiv_zvm != wwpn_npiv_db and
0 != connections and 0 != reserved)
```
to
```
if (wwpn_npiv_zvm != wwpn_npiv_db and
(0 != connections or 0 != reserved))
```
> [fcp-template] rename the variable names on ZCC

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
The new parameter port_type could be ACCESS or TRUNK, when
not specified, it is ACCESS. Then the NICDEF statment is added
'PORTTYPE ACCESS' or 'PORTTYPE TRUNK'.
> [master]Add a new parameter to specify port_type in couple_nic_to_vswitch

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
A new parameter was added to specify port_type in
couple_nic_to_vswitch. But it should only be specified
to VLAN AWARE vswitch.
The code is updated to use vlan_id > 0 to decide the vswitch
is VLAN AWARE, then add PORTTYPE option.
> [master]Do not add PORTTYPE option to a VLAN UNAWARE vswitch

- zvmsdk/dist.py
- zvmsdk/tests/unit/test_dist.py
Add code logic to parse MTU value from network info
and set to network configuration scripts for RHEL.
> [master]Support MTU configuration for VM's NIC in RHEL

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
The 3 new values are: online cpu number, OS distro and kernel version.
> [master] Add 3 new returned values in guest_get_info

- zthin-parts/zthin/bin/refresh_bootmap
- zthin-parts/zthin/bin/unpackdiskimage
- zvmsdk/dist.py
- zvmsdk/tests/unit/test_dist.py
Leverage dracut cmdline 'ip=' to set MTU when deploy RHCOS with
scsi image.
Add new parameter - dns, to support customize nameservers.
> Support set MTU when setup RHCOS network interface

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/tests/unit/test_vmStatus.py
- smtLayer/vmStatus.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/healthy.py
Add status healthy wsgi 
GET /healthy 
is supported so that we can report such
```
{"totalSuccess": 0, "totalFail": 0, "lastSuccess": "", "lastFail": "", "continueousFail": 0, "healthy": true}
```
> Add wsgi handler for status report

- zvmsdk/tests/unit/test_api.py
```
pep8: commands succeeded
```
> [master]add missing UT for zvmsdk api

- zvmsdk/database.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/volumeop.py
In this PR:
1. Remove maxLength for fcp_template_id_list since we have the fcp tmpl id check.
2. When creating fcp template, if not set storage_providers, its default value is None. Then error will be raised.
> Remove maxLength for fcp_templ_id_list and fix bug for creating fcp tmpl

- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/volumeop.py
when creating a fcp template, change parameters description and fcp_devices
from required to optional to make it consistent with nova api.
> change description and fcp_devices to optional

- doc/source/errcode.csv
- doc/source/zvmsdk.conf.sample
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/config.py
- zvmsdk/database.py
- zvmsdk/returncode.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
In this PR:
1. if user specifies min_fcp_paths_count when creating or editing fcp template, this attibutes will be saved to template table.
2. add parameter min_fcp_paths_count for api volume_refresh_bootmap
> Add support for min_fcp_paths_count.

- zvmsdk/database.py
- zvmsdk/volumeop.py
1. Removed the unneccessary check for min_fcp_paths_count when create and edit fcp template.
2. Replace backslash with parentheses for long multi-lines string.
> Update code for min_fcp_paths_count, and optimize format

- zvmsdk/volumeops/templates/rhel7_attach_volume.j2
- zvmsdk/volumeops/templates/rhel7_detach_volume.j2
- zvmsdk/volumeops/templates/rhel8_attach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
- zvmsdk/volumeops/templates/sles_attach_volume.j2
- zvmsdk/volumeops/templates/sles_detach_volume.j2
- zvmsdk/volumeops/templates/ubuntu_attach_volume.j2
- zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
Only modprobe dm_multipath is not enough when executing attach detach
scripts, should make sure multipathd service is active.
> Check status of multipathd service in attach detach scripts

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
when upgrade from ICIC 1.1.4, the fcp table has no WWPNs
if directly upgrade to 1.1.6, will has no WWPNs for in-use FCP devices.
and when sync database, current code will not sync wwpns of in-use FCP devices.
as a result, after upgrade, there is no wwpns for in-use FCP devices.
for issue: https://github.ibm.com/zvc/planning/issues/10248
> fix bug when sync wwpns of fcp

- zvmsdk/database.py
- zvmsdk/volumeop.py
Thanks to `def get_fcp_conn` begins a sqlite transcation explicitly,
we should put all the dependent DDLs and DMLs and DQL statements into the `with get_fcp_conn` block
> put_dependent_DML_DQL_in_one_transcation

- doc/source/errcode.csv
- doc/source/zvmsdk.conf.sample
- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/config.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
The commit include changes:
- Change the user direct statement from "COMMAND SET SHARE"
to use "SHARE RELATIVE XXX" Directly.
- Update default value of user_default_share_unit in zvmsdk.conf
from 0 to 100.
- Update "SHARE RELATIVE XXX" statement accordingly when
a VM resizes its CPUs, including live resize and cold resize.
- Update doc accordingly.
> [master]Add cpu resize support for share unit

- zthin-parts/zthin/bin/refresh_bootmap
use zipl on compute node when refresh_bootmap rhel9 image
still use zipl in image when refresh_bootmap rhel7 or rhel8 image
> update refresh_bootmap to support rhel9

- zvmsdk/exception.py
This PR is used to correct SDKObjectAlreadyExistError class to fix TypeError issue.
> Correct SDKObjectAlreadyExistError class

- zvmsdk/volumeop.py
when there is no FCP configured in the z/VM LPAR and even if SMAPI is down, we should let sdkserver service to start normally.
https://github.com/openmainframeproject/feilong/issues/675
> ignore errors from sync_db when restart sdkserver

- zvmsdk/volumeops/templates/rhel7_attach_volume.j2
- zvmsdk/volumeops/templates/rhel7_detach_volume.j2
- zvmsdk/volumeops/templates/rhel8_attach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
- zvmsdk/volumeops/templates/sles_attach_volume.j2
- zvmsdk/volumeops/templates/sles_detach_volume.j2
- zvmsdk/volumeops/templates/ubuntu_attach_volume.j2
- zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
lszfcp -P sometimes has no output, so need retry and if still no output will use wwpns under /sys/bus/ccw/drivers/zfcp/.
> retry when lszfcp -P sometimes has no output

- doc/source/errcode.csv
- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/returncode.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
replace all `fcp template` or `fcp device template` to `FCP Multipath Template`
> replace all `fcp template` or `fcp device template` to new name

- zvmsdk/volumeop.py
- zvmsdk/volumeops/templates/rhel7_detach_volume.j2
- zvmsdk/volumeops/templates/rhel8_detach_volume.j2
- zvmsdk/volumeops/templates/sles_detach_volume.j2
- zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
because lszfcp sometimes has no output
we can not depend on it when detach, so use the wwpns in parameters directly.
> use wwpns in parameters directly when configure detach

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
because the userid is new created when call guest_deploy
> remove purge reader process in guest_deploy

- zvmsdk/tests/unit/test_utils.py
- zvmsdk/utils.py
- zvmsdk/volumeop.py
When attaching a volume, the following functions are called sequentially
- get_volume_connector()
- attach()
When detaching a volume, the following functions are called sequentially
- detach() 
- get_volume_connector() 
This PR implements a synchronized lock with specified lock name to decorate the above functions.
So that volume attachment and/or detachment are sequentially processed against each VM
> change the attach/detach lock in ZCC layer to a Per-VM-level lock

- smtLayer/changeVM.py
- smtLayer/tests/unit/test_changeVM.py
The PR changes `def undedicate()` in smtLayer/changeVM.py
- Before this PR, the function
- first, run cmd-a (Image_Device_Undedicate_DM)
- if rc == 0, 
- run cmd-b (Image_Device_Undedicate)
- With this PR, the function
- first, run cmd-a (Image_Device_Undedicate_DM)
- if rc == 0 or (rc == 404 and rs == 8)
- run cmd-b (Image_Device_Undedicate)
> fix FCP leftover when detach the last volume

- smtLayer/getVM.py
when calling extract_fcp_data, if smcli return abnormal formatted data:
1. wrong type of the msg, because rh.printLn will accept a type of
string, not a tuple
2. rh.printLn will also put msg into return data, this will cause the upper
layer can not extract correct info. so change to use rh.printSysLog.
3. what's more, sometimes the smcli return a line only contains a #, skip
this line in this scenario.
> fix bug in extract_fcp_data

- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Add param 'do_rollback' for the functions:
- def _do_detach
- def _do_attach
The functions contain multiple phases;
if 'do_rollback' is True (the default), rollback will be done if any phase fails. Otherwise, we try completing as many phases as possible, i.e. no rollback will be done if any phase fails.
> add param 'do_rollback' for volume attach and detach

- zthin-parts/zthin/bin/refresh_bootmap
we require multipath available for the server to boot, so abort the deploy if 0 or only 1 path detected.
> Report error if only 1 path is found when BFV

- zvmsdk/dist.py
- zvmsdk/tests/unit/test_dist.py
Changes code to write multi NICs configuration into one netplan yaml file for Ubuntu 20 and Ubuntu 22.
Because network setup in netplan yaml file does not support gateway set as empty string, so make gateway set for all NICs, no matter it is primary or no primary.
> [master]Network: Support deploy Ubuntu 20 and 22 with multi NICs

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
issue:https://github.ibm.com/zvc/planning/issues/13912
code change: userid definition use GB if the memory is  integral multiple 1024M
> [master] change userid create memory from M to G if is integral multiple

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
1, Check if the user direct contains short format `CPU XX`:
--> if yes, then count short format `CPU XX `to as current CPU definition
--> if no, then count long format `COMMAND DEFINE CPU XX TYPE IFL` as current CPU definition
2, In the resize_cpu function, no matter resize up or resize down:
--> delete all short format `CPU xx`
--> handle the long format `COMMAND DEFINE CPU XX TYPE IFL` to make it correct to match with the VM's cpu value defined in openstack
3, Only return impacted(added or deleted) only format `COMMAND DEFINE CPU XX TYPE IFL`
1, Compare vm current active cpu count <--> target count:
--> if  current active < target, live resize up. How to do it, refer to item2.
--> if current active > target, live resize down, by disable cpus `chcpu -d XX` 
2, get offline cpu address by …
> Correct cpu definition numbers during resize

- smtLayer/makeVM.py
- smtLayer/tests/unit/test_makeVM.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
Replace it with COMMAND DEFINE STOR INITIAL STANDBY REMAINDER
Changes:
- For creating zvm guest, add COMMAND DEFINE STOR INITIAL STANDBY REMAINDER
into user direct, not the COMMAND DEFINE STOR RESERVED xx statment anymore
- For resizing a zvm guest memory, when the zvm user direct contains
COMMAND DEF STOR RESERVED xx, replace it with COMMAND DEF STOR INITIAL
STANDBY REMAINDER.
- Update UT cases.
> Remove DEF STOR RESERVED statment from user direct 

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
Add a parameter meta_data in guest_create
Add parameter meta_data to support the indicated userid
when creating the virtual machine.
userid is used to create the virtual machine and if meta_data
has data, it includes openstack instance id in a dict:
{'openstack_instance_id': instance.name}
This argument can be extended for future use.
> Support indicated userid

- zvmsdk/constants.py
- zvmsdk/hostops.py
- zvmsdk/tests/unit/test_hostops.py
When "$HOME/.zvmsdk_hypervisor_hostname_suffix" file exists, host_get_info will return zvm_host and hypervisor_hostname as `<hypervisor_hostname>.<suffix>` .
`<suffix>` is read from $HOME/.zvmsdk_hypervisor_hostname_suffix .
> Implement the mechanism to return hypervisor hostname with suffix

- zthin-parts/zthin/bin/unpackdiskimage
issue: https://github.ibm.com/zvc/planning/issues/14277
code change:  extend last lvm partition by pvresize
> [master]support lvm partition extend support

- zvmsdk/tests/unit/test_utils.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/utils.py
- zvmsdk/volumeop.py
- By filtering the result of Linux command zhypinfo by layer,
- :param layer: (str) possible values are cpc, lpar, zvm and all.
- :return zhyp_info: (dict) contain the layer(s) specified by param layer
- including cpc name, cpc SN, lpar name, etc.
> add_util_to_return_cpc_info

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/volumeop.py
code change:
change return of edit_fcp_template add orphan values in return value dict
result example:
```
{
'fcp_template': {
'name': 'bjcb-test-template',
'id': '36439338-db14-11ec-bb41-0201018b1dd2',
'description': 'This is Default template',
'host_default': True,
'storage_providers': ['sp4', 'v7k60'],
'min_fcp_paths_count': 2,
'pchids': {
'add' : ['C'],
'delete' : {
'all': ['D', 'E'],
'not_exist_in_any_template': ['F']
},
'all' : ['A', 'B', 'C']
}
}
}
```
> [master] add pchids not-exist-in-any-template in the response of edit_fcp_template API

- scripts/zvmsdk-getpchid
- setup.py
- zvmsdk/database.py
- zvmsdk/utils.py
The command zvmsdk-getpchid does the following:
- generates a log in /var/log/zvmsdk/
- returns the PCHIDs and FCP devices from all FCP multipath templates.
- for example:
```json
{
"cpc_sn": "0000000000082F57",
"cpc_name": "M54",
"hypervisor_hostname": "BOEM5401",
"lpar": "ZVM4OCP1",
"pchids": [
{
"pchid": "021C",
"fcp_devices": "1B16 - 1B17",
"fcp_devices_count": 2
},
{
"pchid": "0260",
"fcp_devices": "",   <--- no FCP devices is allocated from this PCHID so far via any FCP multipath template
"fcp_devices_count": 0
}
]
}
```
> zcc_tool_to_get_pchids_info_from_all_fcp_templates

- zvmsdk/api.py
- zvmsdk/database.py
- zvmsdk/sdkwsgi/handlers/volume.py
- zvmsdk/sdkwsgi/schemas/volume.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_volume.py
- zvmsdk/tests/unit/sdkwsgi/test_handler.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
- API interface change:
- PCHID usage info will be passed in
- return more info:
- the PCHID of each allocated FCP,
- whether new FCP devices are allocated or reused, whether FCP devices are released.
- When allocating new FCP devices to VM, take the PCHID free capacity into consideration
- PCHID load balance. (select the most free PCHIDs as possible)
- real multipath from PCHID layer. (select different PCHIDs for different paths as possbile)
```python
def get_volume_connector(self, assigner_id, reserve,
fcp_template_id=None, sp_name=None, pchid_info=None):
if reserve:
is_reserved_changed, fcp_list, fcp_template_id = 
self.fcp_mgr.allocate_fcp_devices(assigner_id, fcp_template_id,
sp_name, pchid_info)
else:
is_reserved_changed, fcp_list = 
self.fcp_mgr.release_fcp_devices(assigner_id, …
```
> get_volume_connector_based_on_pchid_info

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- fix sqliteRow indexError when running command zvmsdk-getpchid
```python
[root@112-cmp-wdl ~]# /usr/bin/zvmsdk-getpchid
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/zvmsdk/database.py", line 118, in get_fcp_conn
yield _FCP_CONN
File "/usr/bin/zvmsdk-getpchid", line 119, in get_fcp_devices_per_pchid
inuse_pchids = fcp_mgr.db.get_pchids_of_all_inuse_fcp_devices()
File "/usr/lib/python3.6/site-packages/zvmsdk/database.py", line 1835, in get_pchids_of_all_inuse_fcp_devices
item[key] = item[key].upper()
IndexError: No item with that key
```
> fix_sqliteRow_indexError_when_running_command_zvmsdk-getpchid

- doc/source/errcode.csv
- zvmsdk/returncode.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Before this fix, when calling the get_volume_connector:
if 
1. fcp_multipath_template is not specified which means to use default template, and 
2. some PCHID info is not contained in the pchid_info 
Then the following keyerror would be reported:
`Failed to reserve FCP devices for assigner xj00000e by FCP Multipath Template aee11840-5185-11ee-b8ec-02010d42ff55 error: Database operation failed, error: Execute SQL statements error: '0240'`
This fix makes the following changes:
1. the check of pchids_info to a later stage after the FCP multipath template is selected based on the default rule.
2. Enhance the error msg, avoid printing the whole pchids_info as it will contain all the PCHIDs info of the CPC which can be very long string.
> move the check of pchids_info to later stage after FCP multipath template is set

- zvmsdk/constants.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
- For resizing a zvm guest memory, when the zvm user direct contains 
- COMMAND DEF STOR RESERVED xx,
-  COMMAND DEF STORAGE RESERVED xx, 
- COMMAND DEFINE STOR RESERVED xx, 
- COMMAND DEFINE STORAGE RESERVED xx, 
- COMMAND DEF ST RESERVED xx,
- COMMAND DEFINE ST RESERVED xx
replace it with COMMAND DEF STOR INITIAL STANDBY REMAINDER.
- Update UT cases.
> Support more DEF STOR statment format when resizing zvm guest memory

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
only select the FCP devices whose PCHIID has free capacity
- Examples:
```python
free capcity of PCHIDs =  {'A':1, 'B':3, 'C':2, 'D':2}
|--- PCHID ----|   
FCP combinations                A    B    C    D        weight  valid(>=1)
---------------------------------------------------------------------------
1a01(A) 1b01(A) 1c01(C)    min( 0.5       2        )  = 0.5     No
1a02(A) 1b02(B) 1c02(C)    min( 1    3    2        )  = 1       Yes   --|___ random select one
1a03(A) 1b03(D) 1c03(D)    min( 1              1   )  = 1       Yes   --|
```
> check_pchid_free_capability_for_get_fcp_pair_with_same_index

- zvmsdk/tests/unit/test_utils.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/utils.py
- zvmsdk/volumeop.py
Problem:
When CHPID virtualization is enabled, lschp command does not output the real PCHID info.
This fix change the method to get PCHID:
1. Check whether chpid virtualization is enabled with following cmd:
```
[root@quality-ssi003 ~]# vmcp q chpidv
One path CHPID Virtualization is on
```
```
[root@m5402011 ~]# vmcp q chpidv
CHPID Virtualization is off
```
2. If off, use original cmd `lschp` to get the PCHID.
3. otherwise, use `vmcp q chpid xx pchid` to get the PCHID.
> change the method to get PCHID to tolerate the SSI scenario

- zvmsdk/database.py
- zvmsdk/tests/unit/test_database.py
For example, when the fcp template has 2 paths, and the first path has 2 FCP devices and the second has 1. When enable get_fcp_pair_with_same_index, will raise IndexError.
This PR is to fix this issue.
> Fix issue: when the fcp count is different in differnt paths, raise IndexError

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
After deleting BFV VMs, their consumed fcps are unreserved in ZCC db, however, the state of those fcps are still 'Active'. Now calling a sync_db_with_zvm() to ensure the state to be updated to 'free'.
> Sync ZCC db with ZVM after release fcps.

- zvmsdk/vmops.py
Let `GetGuestInfo()` return an integer instead of a float for `max_mem_kb` field when the guest is powered off.
Fixes #766.
> Let GetGuestInfo() return int for max_mem_kb

- zvmsdk/sdkwsgi/handlers/tokens.py
When running the command 
```
$ curl http://localhost/ -H "Content-Type:application/json" -H 'X-Auth-Token:<user token>'
```
with the user token provided by the `CreateToken()` function, one systematically gets:
```
HTTP status: 401, body: {"overallRC": 400, "rc": 400, "rs": 401, "modID": 120, "output": "", "errmsg": "This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required."}
```
The logs in DEBUG mode show the message:
```
[2023-12-12 22:16:57] [DEBUG] token not valid
```
After debugging, it appears that the function `jwt.decode()` now needs a third argument with the decoding algorithms, as shown by this small python …
> Fix auth mechanism 2/3

- zvmsdk/sdkwsgi/handlers/tokens.py
This PR only fixes typos in log messages.
> Fix auth mechanism 3/3

- zvmsdk/sdkwsgi/requestlog.py
When trying to create an authentication token:
```
$ curl http://localhost/token -X POST -i -H "Content-Type:application/json" -H "X-Admin-Token:zvX2mFxuj8HcrYkAacLReV0RTQ0K5IIEighOR9F8AG"
```
a "502 bad gateway" is returned:
```
HTTP/1.1 502 Bad Gateway 
Server: nginx/1.18.0 (Ubuntu) 
Date: Mon, 11 Dec 2023 21:17:48 GMT 
Content-Type: text/html 
Content-Length: 166 
Connection: keep-alive 
<html> 
<head><title>502 Bad Gateway</title></head> 
<body> 
<center><h1>502 Bad Gateway</h1></center> 
<hr><center>nginx/1.18.0 (Ubuntu)</center> 
</body> 
</html>
```
Log file `/var/log/nginx/error.log` contains
```
2023/12/11 21:32:02 [error] 665#665: *15 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /token HTTP/1.1", …
```
> Fix auth mechanism 1/3

- doc/source/parameters.yaml
- doc/source/restapi.rst
In the API doc, some `userid` parameters are marked as if they were in the `path`, while they are in the `body`.
This PR fixes the 4 cases I have found.
7.5.11. Set FCP Usage
```
userid path string Guest userid
->
userid body string Guest userid.
```
7.8.4. Grant user to vswitch
```
grant_userid path string Guest userid
->
grant_userid body string Guest userid.
```
7.8.5. Revoke user from vswitch
```
revoke_userid path string Guest userid
->
revoke_userid body string Guest userid.
```
7.8.6. Set user VLANID to vswitch
```
userid path string Guest userid
->
userid body string Guest userid.
```
> Doc: Fix userids that are in body, not in path

- zvmconnector/connector.py
It is currently impossible to use authentication tokens from a python client program.
Reason is that on client side, you do not have the `/etc/zvmsdk.conf` file where you could define `auth = token`. The only way to pass such an option is via parameters, but this is not currently implemented.
This PR adds an `auth` parameter to the ZVM connector methods, which is then passed on to the REST client.
Python program used for testing:
```
from zvmconnector import connector
client = connector.ZVMConnector(
connection_type = 'rest', ip_addr = '1.2.3.4', port = '443', ssl_enabled = True, verify = 'feilongCA.crt',
token_path = 'token.txt', auth = 'token')
userid = 'myguest'
vcpus = 2
memory = 2048
user_profile = 'osdflt'
disk_list = [
{
'size': "5g",
'is_boot_disk': True,
'disk_pool': …
```
> Fix token authentication on the client side

- doc/source/parameters.yaml
- doc/source/restapi.rst
This PR synchronizes the documentation with the code of `get_linux_dist()`:
```
supported = {'rhel': ['6', '7', '8', '9'],
'sles': ['11', '12', '15'],
'ubuntu': ['16', '20', '22'],
'rhcos': ['4']}
```
`rhel8.x`, `rhel9.x`, `sles15.x`, `ubuntu20.x`, and `ubuntu22.x` were missing in the doc.
These texts are used in:
* documentation parameter `image_metadata`
for `Create image`
* documentation parameter `guest_os_version`
for `Attach volume`, `Detach volume`, `Delete network interface`, and `Grow root volume of guest`
* documentation parameter `guest_os_version_all`
for `Create network interface` and `List images`
I tried to follow all code paths and it seemed to me they all call `get_linux_dist()`. Please double-check as I am new to Feilong's source code, and an error is always possible.
> Doc: update list of supported operating systems

- doc/source/parameters.yaml
`Show Guest definition` and `Get Guest user direct` API calls return only `user_direct`.
They could also return as "checked info"  a boolean `nic_coupled` if they were coded to call `VMOps.get_definition_info()` in a certain manner, but as far as I can see, they aren't.
This PR removes mention of checked info result from the doc.
> Doc: There is no "check info result"

- zvmsdk/tests/fvt/api_templates/test_guest_create_network_interface.tpl
`active` field is defined as a boolean, but the example shows it as a string.
This PR fixes the example.
> Doc: True is a boolean, not a string

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/tests/fvt/api_templates/test_guests_get_interface_stats.tpl
- zvmsdk/tests/fvt/api_templates/test_guests_get_stats.tpl
Current documentation at https://cloudlib4zvm.readthedocs.io/en/latest/restapi.html#get-guests-interface-stats and at https://cloudlib4zvm.readthedocs.io/en/latest/restapi.html#get-guests-stats-including-cpu-and-memory
has no detailed field description nor complete example.
This PR fixes that.
> Doc: Add content for "Get Guests interface stats" and "Get Guest stats including cpu and memory"

- zvmconnector/restclient.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/tests/unit/sdkclientcases/test_restclient.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
This problem wasn't exposed because we always use the default value of False before in the deployment. But it has the problem when we try to pass the "Active=True" in attach_interface.
> Fix the bug of argument active in guest_create_network_interface

- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
When one tries to run the example at https://cloudlib4zvm.readthedocs.io/en/latest/restapi.html#attach-volume
i.e.
```
{
"info":
{
"connection":
{
"assigner_id": "username",
"zvm_fcp": "1fc5",
"target_wwpn": "0x50050763050b073d",
"target_lun": "0x4020400100000000",
"os_version": "redhat7",
"multipath": True,
"mount_point": "/dev/sdz",
"is_root_volume": False
}
}
}
```
the following exception is thrown:
```
HTTP status: 500, body: {"overallRC": 500, "modID": 100, "rc": 500, "rs": 1, "errmsg":
"Unexpected internal error in ZVM SDK, error: (127.0.0.1:46170) SDK server got unexpected exception:
AttributeError(\"'bool' object has no attribute 'lower'\")", "output": ""}
```
This PR fixes this problem.
> Multipath is a boolean, not a string

- doc/source/parameters.yaml
One missing parameter found when comparing to source code.
> Doc: Missing parameter for "Create network interface"

- zthin-parts/zthin/bin/refresh_bootmap
- In refresh_bootmap, retry 10 times for each fcp to get target wwpns from ether lszfcp output or /sys/bus/ccw/drivers/zfcp/0.0.$fcp/
- refer to previous PR example of xxx_attach_volume.j2
- https://github.com/openmainframeproject/feilong/pull/676
> retry to get fcp target wwpn in refresh_bootmap

- zvmsdk/database.py
- zvmsdk/tests/unit/test_volumeop.py
- zvmsdk/volumeop.py
Update the API of get_fcp_template_details to return physical wwpns
> Update the API of get_fcp_template_details to return physical wwpns

- zvmsdk/sdkwsgi/validation/parameter_types.py
- zvmsdk/tests/unit/sdkwsgi/handlers/test_guest.py
The character underline(_) is not supported by smapi, so remove it and only support letters and numbers.
> [master]Change userid pattern to only support letters and numbers

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
Check if the userid has already been granted for the vswitch, if yes, then do nothing. Otherwise, it will cause the existing NICs in the VM down on the vswitch.
> Avoid the duplicated granting userid to vswitch

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/smtclient.py
- zvmsdk/tests/fvt/api_templates/test_guest_disk_info_output.tpl
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
This PR adds missing GET operation for the list of minidisks of a guest:
```
GET /guests/{userid}/disks
```
This PR solves issue #796.
It contains changes to:
* zvmsdk
* zvmconnector
* unit tests
* documentation
> Add API call to get minidisks list

- zvmsdk/returncode.py
- zvmsdk/smtclient.py
z/VM: Fail to resize memory, but the error message wrongly reports `fail to resize CPU`.
**Changes for fix**:  
change `rs` code for error in `live_resize_memory`: `7` ==> `17`(newly defined for memory error)
> Fix[SMT]: Update rs code for error in live_resize_memory

- doc/source/zvmsdk.conf.sample
- zvmsdk/config.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
https://github.ibm.com/zvc/planning/issues/10607
previous config:
swap_force_mdisk: False only works for swap only case( disk_pool is None, bfv + swap)
new config:
swap_default_with_mdisk: True   applies for all the cases when disk_pool is not None (including bfv+swap), if True, create swap with mdisk, if False, create swap device with vdisk
> [master]support create swap device with vdisk

- doc/source/parameters.yaml
- doc/source/restapi.rst
- smtLayer/tests/unit/test_vmStatus.py
- smtLayer/vmStatus.py
- zvmconnector/restclient.py
- zvmsdk/sdkwsgi/handler.py
- zvmsdk/sdkwsgi/handlers/smapi.py
- zvmsdk/tests/fvt/api_templates/test_smapi_health.tpl
This PR adds the missing fields to the output of "Report health of SMAPI" (see issue #774).
It preserves ascending compatibility by introducing a new API call with a slightly different URL:
**GET /smapi_health**
instead of **GET /smapi-healthy**.
The old call still exists with the old behaviour, but is documented as "deprecated".
```
{
"SMAPI": {
"totalSuccess": 0,
"totalFail": 0,
"lastSuccess": "",
"lastFail": "",
"continuousFail": 0,
"healthy": True
}
}
```
```
{
"rs": 0,
"overallRC": 0,
"modID": null,
"rc": 0,
"errmsg": "",
"output": {
"totalSuccess": 0,
"totalFail": 0,
"lastSuccess": "",
"lastFail": "",
"continuousFail": 0,
"healthy": True
}
}
```
> SMAPI health

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
* Set maximum number of virtual processors to its default value if empty max cpu number defined in `MACHINE ESA`
* The default `max_cpus` value is either 1 or the number of CPU statements for this user, whichever is greater.
* Update UT for default `max_cpus`
> SSC: tolerate the empty max cpu number in MACHINE ESA

- zthin-parts/Makefile
Removed the `ifeq ($(OS_IS_RHEL8),1)` flag in the zthin-parts makefile to avoid encountering error
> Update zthin makefile to remove flag

- .gitignore
- doc/ext/restapi_parameters.py
- doc/source/errcode.csv
- doc/source/parameters.yaml
- doc/source/zvmsdk.conf.sample
Fixed by import sphinx.util.logging to log info and warnings
Error:
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 281, in build_main
app.build(args.force_all, args.filenames)
File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 347, in build
self.builder.build_update()
File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 312, in build_update
len(to_build))
File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", …
```
> fix readthedocs errors

- doc/source/zvmsdk.conf.sample
- smtLayer/tests/unit/test_vmUtils.py
- smtLayer/vmUtils.py
- zvmsdk/config.py
- zvmsdk/smtclient.py
* add `smapi_socket_long_call_timeout_seconds` configuration in `zvmsdk.conf`
* add `smapi_socket_timeout_seconds` configuration in `zvmsdk.conf`
* take `VMRELOCATE` as long-duration operation
* use `smapi_socket_long_call_timeout_seconds` as timeout parameter when executing long-duration SMAPI
* use `smapi_socket_timeout_seconds` as timeout parameter when executing general SMAPI
> Support SMAPI timeout configuration

- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_smtclient.py
Sometimes live resize (increase) cpus on SLES VM can't bring the new added offline cpu online, but can make it present then the next resize can bring it online.
Hence, always call 'chcpu -e' to enable the new added cpus.
> Fix the problem of live resize cpus for SLES VM

- zvmsdk/sdkwsgi/handlers/guest.py
To Support comments in user directory, It is discussed in detail in case " https://github.ibm.com/zvc/planning/issues/18693 "
--signed off : [ssanthosh@in.ibm.com](mailto:ssanthosh@in.ibm.com)
> Add support for comment in user direct

- doc/source/setuphttpd.rst
Updated `setuphttpd.rst` to include installation instructions for SLES
> Docs: Installation instructions for SLES

- doc/source/quickstart.rst
Updated `quickstart.rst`
PR forwarded from https://github.com/openmainframeproject/feilong/pull/832
> Docs: Updated quickstart with OBS Package install for RPM and SLES

- zvmconnector/restclient.py
- zvmsdk/api.py
- zvmsdk/sdkwsgi/handlers/guest.py
- zvmsdk/sdkwsgi/schemas/guest.py
- zvmsdk/smtclient.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_smtclient.py
- zvmsdk/tests/unit/test_vmops.py
- zvmsdk/vmops.py
What this PR does / why we need it:
The code will help successful CPU resize Operation by preserving the custom CPU share deployed by the customer.
Which issue(s) this PR fixes(unless minor typo change ,better to have an issue opened):
https://github.ibm.com/zvc/planning/issues/18693
Special notes for your reviewer:
**There is a dependent PR for this in icic-dev repo, " https://github.ibm.com/zvc/icic-dev/pull/6088 "  both of the PR's should be merged together**
Results are attached here :
https://github.ibm.com/zvc/planning/issues/18693#issuecomment-88412796
https://github.ibm.com/zvc/planning/issues/18693#issuecomment-88412883 
https://github.ibm.com/zvc/planning/issues/18693#issuecomment-88499911 << resize with VM shutdown
[optional] which components (compute, zvm/kvm etc)
zvm …
> Resize CPU with custom cpu share

- smtLayer/migrateVM.py
There are possibility of error
local variable 'codes' referenced before assignment
this commit is to fix it.
> Avoid error of variable referenced before assignment

- .github/workflows/package.yaml
This feature allows us to use the `build-zvmsdk` repository to build the feilong packages for `zthin` and `zvmsdk` using OBS.
The theory behind this action is that on each push to the master branch on feilong, the github action will dispatch an event to the `build-zvmsdk` repo which will trigger it's own action to run scripts to generate new tarballs. 
- When `build-zvmsdk` receives the dispatched event from this (feilong) github action, it first runs a few script files to generate new tarballs from the latest version of the feilong master branch. 
- After creating all the source files, it downloads them as artifacts and pushes them to the master branch of `build-zvmsdk`.
- Once `build-zvmsdk` has a push, it triggers the webhook with OBS which causes each package hosted on OBS to download …
> Automating Feilong Package Building using Github Action

- doc/source/setuphttpd.rst
> Docs: Update webserver setup instructions

- doc/source/restapi.rst
- doc/source/setuphttpd.rst
Documentation changes:
* fix a minor indentation problem in httpd setup chapter
* Separate `/guests` and `/volumes` namespaces in API chapter
Small part of fixing https://github.com/openmainframeproject/feilong/issues/772
> Add a "Volume(s)" section to API documentation

- README.md
This replaces links to the old documentation https://cloudlib4zvm.readthedocs.io/en/latest/index.html and the old bugs https://bugs.launchpad.net/python-zvm-sdk/+bug which will be cleaned up and removed.
> Fix doc building and new links for docs and bugs the README

- .github/workflows/pr_ut_py311.yaml
- tox.ini
This will allow the Pull Request Check Test github action to complete properly for all PRs.
The flake8 test for [restclient.py](https://github.com/mfriesenegger/feilong/blob/b77a8ff51dacb2928a55915bcfe40f9b83787224/zvmconnector/restclient.py#L1143) fails with [E721](https://www.flake8rules.com/rules/E721.html).  I have added E721 to the [ignore](https://github.com/openmainframeproject/feilong/compare/master...mfriesenegger:feilong:update-unit-test-python-version?expand=1#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R24) option in tox.ini.
> Update Pull Request Check Test python version

- doc/source/parameters.yaml
- doc/source/restapi.rst
- zvmsdk/tests/fvt/api_templates/test_get_fcp_usage.tpl
- zvmsdk/tests/fvt/api_templates/test_get_switch_record.tpl
- zvmsdk/tests/fvt/api_templates/test_volume_attach.tpl
- zvmsdk/tests/fvt/api_templates/test_volume_attach_detach.tpl
- zvmsdk/tests/fvt/api_templates/test_volume_detach.tpl
Documentation fixes
1) Move method to vswitch section
* Get vswitch info
2) Fix typography and English
3) Fix parameters of existing volume functions
* Refresh volume bootstrap info
* Get volume connector
* Attach volume
* Detach volume
* Get FCP usage
* Set FCP usage
4) Add FCP templates API calls
* Create FCP template
* Delete FCP template
* Get FCP templates
* Edit FCP template
* Get FCP templates details
5) Remove unused parameters
Fixes #772
> Doc: FCP templates API calls and other fixes

- zvmsdk/volumeops/templates/sles_attach_volume.j2
On SLES, the desired device in `/dev` was not created by `AttachVolume()` API call.
Root cause was that path to `scsi_id` utility is `/usr/lib/udev/scsi_id` on SLES, and not `/lib/udev/scsi_id` like in the current configuration script. This PR fixes that path.
This PR also:
* uses simpler bash syntax for increments and decrements
* copies some comments from the script for RHEL
* fixes typos and English
in that configuration script.
> Fix volume configuration script for SLES

- scale_test/create.py
- smtLayer/smtTest.py
- smtLayer/vmStatus.py
- zvmsdk/api.py
- zvmsdk/config.py
- zvmsdk/database.py
- zvmsdk/hostops.py
- zvmsdk/log.py
- zvmsdk/smtclient.py
- zvmsdk/tests/fvt/test_guest.py
- zvmsdk/tests/fvt/test_utils.py
- zvmsdk/tests/fvt/test_volume.py
- zvmsdk/tests/unit/test_api.py
- zvmsdk/tests/unit/test_config.py
- zvmsdk/tests/unit/test_hostops.py
- zvmsdk/tests/unit/test_smtclient.py
Multiple disk pool support is added for the zvmsdk.
1. ZVMSDK allows user to add 10 disk pool
2. While creating VM, user has to pass disk_pool name if user configures multiple disk pool
3. No need to pass disk_pool name if user configures one disk pool
> Add multiple disk pool support for the zvmsdk

- CODE_OF_CONDUCT.md
- tox.ini
Replaced the code of conduct: the existing link was deprecated.
Piggyback: ignore a flake8 error about unused global variables.
> Replaced code of conduct

- zthin-parts/zthin/include/vmapiVirtual.h
Max characters need to be 16
pending state has 7 chars and member state is 
8+1+7 = 16
currently defined is 15 and cmd is failing with pending state members
> Update vmapiVirtual.h to fix incorrect max characters

- zvmsdk/database.py
- zvmsdk/smtclient.py
With current code when you:
1. create a VM guest
2.  attach a disk via `AttachVolume()` to that guest
3. forget to detach it via `DetachVolume()`
4. delete the instance
then the disk stays counted as attached to the deleted instance.
If you recreate the instance, then `AttachVolume()` will skip the dedication, because it considers that the disk is already dedicated to the instance, while it is not.
This PR resets the FCP records in database for the deleted instance at time of deletion.
> Reset FCP assignements of deleted VM

- zvmsdk/sdkwsgi/schemas/guest.py
This PR updates the deploy schema to allow `None` (`null`) as a valid value for the `transportfiles` parameter, along with the existing string type. This fix resolves validation issues where optional string parameters were incorrectly rejecting `None` values, leading to deployment failures.
Fixes #883 
CC @Bischoff
> Allow 'None' as a valid value in deploy schema

- zvmsdk/config.py
This PR updates the auth option in `zvmsdk.conf` to use `token` instead of `auth`. There is no such thing as `auth=auth`. 
```
Whether auth will be used.
When sending http request from outside to running zvmsdk,
Client will be requested to input username/password in order
to authorize the call.
Set this to 'none' indicated no auth will be used and 'auth'
means username and password need to be specified.
Possible value:
'none': no auth will be required
'token': need auth, pyjwt is used to return a token
to caller if the username and password is correct.
```
CC @Bischoff
> Correct WSGI Authentication Option Name from auth to token
